### PR TITLE
lookup: add npm

### PR DESCRIPTION
**Pull request by addaleax**
This was, surprisingly, not in this list. Also, I am not sure, but I *guess* this shouldn’t be merged as long as `npm` is broken on node `master`?

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by MylesBorins** [comment]
If I recall correctly npm test suite wasn’t able to run in our CI… hopefully I’m incorrect :D

**Comment by addaleax** [comment]
If I remember correctly, the main (only?) reason we’re not currently running it is that it makes a lot of network calls, but then again citgm isn’t exactly shy of doing that anyway…

**Comment by gibfahn** [comment]
I assume we normally want to test the vendored copy of npm rather than `latest`, which is what [gibfahn-test-npm](https://ci.nodejs.org/view/All/job/gibfahn-test-npm) and [gibfahn-test-npm-win](https://ci.nodejs.org/job/gibfahn-test-npm-win) do (see also https://github.com/nodejs/build/issues/317 and https://github.com/nodejs/node/pull/11540). I was hoping for review from the npm team, but barring that I'll just land it.

My issue with this is that the npm tests have never passed for me on any platform other than macOS, and seem to be flaky there. See the latest runs of the CI jobs for an example. If we're going to have to mark it as flaky everywhere there's not much point in having it.

**Comment by BridgeAR** [comment]
@gibfahn I guess it would still be useful to have npm run in case the tests pass on OS-X. So we could just skip them everywhere else.

**Comment by gibfahn** [comment]
>@gibfahn I guess it would still be useful to have npm run in case the tests pass on OS-X. So we could just skip them everywhere else.

They're also flaky on macOS...

If someone would like to raise a PR adding npm we can run citgm on it to test. I'm not strongly against adding npm, just skeptical of the benefits.

**Comment by BridgeAR** [comment]
@gibfahn I am not sure what PR you would want besides this one?

**Comment by gibfahn** [comment]
>@gibfahn I am not sure what PR you would want besides this one?

Sorry, got my wires crossed.

Smoker run: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/239/

**Comment by BridgeAR** [comment]
If we can run the npm tests at least on one system, I still think we should do that.

New smoker run: 
10. https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/284/
8. https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/285/

**Comment by targos** [comment]
on Linux:
```
error:                       | 4200 passing (7m)                                                                                                                                
error:                       | 11 pending                                                                                                                                       
error:                       | 28 failing          
```

**Comment by targos** [comment]
Launched https://github.com/targos/citgm/actions/runs/627105955 to check the status.

**Comment by targos** [comment]
It's green! Let's try with more platforms: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/137/

**Comment by richardlau** [comment]
The failure on LinuxONE (s390x) is https://github.com/tapjs/node-tap/issues/691, the underlying cause being emscripten currently lacking support for big endian systems (https://github.com/emscripten-core/emscripten/issues/12387).

**Comment by targos** [comment]
Rebased and skipped s390.

**Comment by targos** [comment]
New CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/142/console

**Review by targos — APPROVED** [review]

**Pull request merged**
