### PR TITLE
lookup: skip moment

### PR DESCRIPTION
**Pull request by BethGriggs**
Moment is currently failing on all platforms - https://github.com/moment/moment/issues/5334

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by BethGriggs** [comment]
citgm-nobuild run on v12.x - https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/lastCompletedBuild/testReport/

**Review by BridgeAR — APPROVED** [review]

**Comment by BethGriggs** [comment]
If I mark something skip=true in CITGM, do I need to wait for a new release of CITGM for that to be taken into account in the `citgm` CI runs?

**Comment by richardlau** [comment]
> If I mark something skip=true in CITGM, do I need to wait for a new release of `citgm` for that to be taken into account in the `citgm` CI runs?

Yes. I can’t do that right now until Sunday at the earliest but maybe someone else could.

**Review by richardlau — APPROVED** [review]

**Review by sam-github — APPROVED** [review]

**Comment by sam-github** [comment]
@BethGriggs maybe use the CITGM job parameter?

> what citgm should npm install: "npm install -g $CITGM" (can be replaced with any npm compatible path)

`npm install -g nodejs/citgm` should install citgm from master, from github.com, so you might be able to use that to run a citgm with your latest lookup.json without waiting for an npm publish.

**Comment by MylesBorins** [comment]
Sam's suggestion is a good one. A couple of thoughts

* There is not need for review lookup changes in our [current governance](https://github.com/nodejs/citgm/blob/master/COLLABORATORS.md)
* numbers are cheap... it is quite easy to quickly publish after landing a change to the lookup (this is how I've done it)
* I [opened an issue](https://github.com/nodejs/citgm/issues/778) for other to get added to publish rights

**Review by MylesBorins — APPROVED** [review]
LGTM

**Comment by MylesBorins** [comment]
also fwiw I've landed this and published a new version of citgm

**Pull request merged**
