### PR TITLE
[WIP] fix: inherit stdio/stderr so that we can test for node #6456

### PR DESCRIPTION
**Pull request by bcoe**
Please note that this pull is currently forked off of https://github.com/nodejs/citgm/pull/135, which made it easier to test.
## Problem

Because CITGM runs tests with spawn's default `pipe` behavior (`isTTY = false`), we are unable to detect the terminal output bug discussed here: https://github.com/nodejs/node/issues/6456

yargs has a regression test for terminal truncation that was not caught.
## Potential Solution

This pull request is a potential solution, rather than using `stdio = pipe`, we use `stdio = inherit`:

**the good:**

We're able to detect the terminal output bug:

_yargs at master:_

``` sh
./bin/citgm yargs
info:    passing module(s)   |                     
info:    module name:        | yargs               
info:    version:            | 4.7.1               
info:    done                | The smoke test has passed.
```

_yargs prior to the [set-blocking](https://www.npmjs.com/package/set-blocking) patch:_

``` sh
./bin/citgm yargs --sha=2df0dba39249549589eb96c95691bff756e84177
npm ERR! Test failed.  See above for more details.
error:   failure             | The canary is dead: 
error:   failing module(s)   |                     
error:   module name:        | yargs               
error:   version:            | 4.7.1               
error:   error:              | The canary is dead: 
error:   error:              |                     
error:   done                | The smoke test has failed.
```
## The Problem With This Solution

Since `stdout` is now equal to `inherit` our test output becomes _pretty_ noisy.
## Ben's Thought of the Day

I _hate_ noisy test output, having said that -- I think it might be worthwhile to have `citgm` run tests with `isTTY = true` like this, its a more realistic test of the behavior of CLI applications.

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
if you rebase against master I've landed the first three commits

**Comment by TheAlphaNerd** [comment]
@bcoe just looked at what is going on here... this ignores the current way we are logging the output and storing it for the logs at the end... is there a way to do this and still collect that info?

**Comment by bcoe** [comment]
@TheAlphaNerd great question, I was trying to think of a way to do so and nothing immediately jumped out at me; I can hammer on this more in my spare time, and see if I can figure out a way to trigger `isTTY = true` regressions, while still collecting output.

**Comment by TheAlphaNerd** [comment]
Could we emulate a tty?

**Comment by bcoe** [comment]
@TheAlphaNerd what if we just make this an option with a CLI flag then, purely hypothetical here, if we were working on a web-hook driven real-time build environment we could opt in to running with `inherit`.

**Comment by TheAlphaNerd** [comment]
I guess it really comes down to how you plan to report. If we inherit and
lose all the out we won't be able to have any useful output to show users
as to what failed.

Not necessarily opposed, just want to figure out if there is a way to do
both. Specifically I'm trying to figure out what tests break with inherit
that don't with our current setup.

**Comment by bcoe** [comment]
@TheAlphaNerd yeah, I hear you. Maybe the answer is simulating a `tty` with a small buffer like OSX -- should be something we can pull off, perhaps just have something that waits a tick every 1024 bytes or something.

**Comment by TheAlphaNerd** [comment]
I think a great first step would be making a small reproducible repo that
passes in the current setup and fails with inherit... Do you think you
could put together an example of that

**Comment by bcoe** [comment]
@TheAlphaNerd with the new `sha` feature, this actually does just that:

`./bin/citgm yargs` <-- master branch of yargs will pass.
`./bin/citgm yargs --sha=2df0dba39249549589eb96c95691bff756e84177` <-- branch of yargs before `set-blocking` fails.

**Comment by TheAlphaNerd** [comment]
@bcoe any thoughts on this?

**Comment by Fishrock123** [comment]
Did this stall out or?

**Comment by bcoe** [comment]
@Fishrock123 @TheAlphaNerd stalled out due to my workload sorry, I'd still love to be able to test with output going directly to `stdout`, since it would have caught some weirdness in terminal flushing on Node 6.x; I had an idea for a compromise, let's make using `inherit` a command line flag.

**Comment by gdams** [comment]
@bcoe any progress on this?

**Comment by MylesBorins** [comment]
I'm going to close this for now due to inactivity, please feel free to reopen

**Pull request closed without merging**
