### PR TITLE
npm: always log the output of npm.install.stdout

### PR DESCRIPTION
**Pull request by TheAlphaNerd**
citgm: https://ci.nodejs.org/job/thealphanerd-smoker/159/

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
This should hopefully resolve the halting problems we were seeing in CI while avoiding so many messages in the logs themselves.

**Comment by Fishrock123** [comment]
Don't have the context to know here, maybe cc @nodejs/npm for a quick review?

**Comment by jasnell** [comment]
LGTM

**Comment by TheAlphaNerd** [comment]
Thanks @jasnell 

@Fishrock123 for context... we are logging the output of the child process. It turns out that not setting up the listener here was causing all sorts of hanging when there was a ton of data in the child process stdout stream... this was rearing it's head in v5 more than v4. I can't exactly reproduce it.. but there is some sort of regression on v5

**Pull request merged**
