### PR TITLE
lookup: add chokidar

### PR DESCRIPTION
**Pull request by targos**
Fixes: https://github.com/nodejs/citgm/issues/446

##### Checklist

- [X] `npm test` passes

#### Hard Requirements

- [X] Module source code must be on Github.
- [X] Published versions must include a tag on Github
- [X] The test process must be executable with only the commands `npm install && npm test` using the tarball downloaded from the Github tag mentioned above
- [x] The tests pass on supported major release lines
- [x] The maintainers of the module remain responsive when there are problems
- [X] At least one module maintainer must be added to the lookup maintainers field

#### Soft Requirements

At least one of:

- [x] The module must be actively used by the community OR
- [x] The module must be heavily depended on OR
- [x] The module must cover unique portions of our API OR
- [ ] The module fits into a key category (e.g. Testing, Streams, Monitoring, etc.) OR
- [ ] The module is under the Node.js foundation Github org OR
- [ ] The module is identified as an important module by a Node.js Working Group

### CODE REVIEW

**Comment by es128** [comment]
Yes

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/5/console

**Comment by es128** [comment]
Ok, so now that I see that output I realize that maybe it does not make sense to add chokidar here like this.

The thing about the test suite is that it is not really made up of unit tests. They're actually integration tests interacting with the file system. And the file system often behaves unpredictably, especially under the type of load caused by the test suite. Sporadic failures that are not indicative of an actionable problem are very common, especially in underpowered VM-based CI environments. And I frequently need to manually restart jobs in Travis to turn the status green.

I've put effort in the past to making the test suite more reliable despite these challenges, and while I've made improvements over prior states it is still problematic.

I'd be open to suggestions like making a scaled down and possibly slower-running version of the test suite for citgm purposes if there is enough desire to follow through on this integration.

**Comment by MylesBorins** [comment]
we should dig more into this

@es128 is all the filesystem stuff happening in a tempdir?

**Comment by es128** [comment]
Just noticed the unanswered question when I got notified of the thread being closed. 

@MylesBorins no it doesn’t use a proper tempdir. Were you thinking it would have a positive or negative impact in test stability if it did? It does generate fixture paths in such a way that each test has its own little sandbox in a fresh directory.

**Pull request closed without merging**
