### PR TITLE
lookup: skip @nearform/flame <8

### PR DESCRIPTION
**Pull request by MylesBorins**
Fails consistently on 8.x and 6.x

/cc @mcollina @bridgear

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by MylesBorins** [comment]
fwiw I checked the last two releases of 8.x and the latest version of 6.x and it fails on all of them

**Comment by mcollina** [comment]
Interesting, this is passing the build on our CI for Node 8.

Node 6 is not really supported, so that's expected.

**Comment by targos** [comment]
That's what I mean. You have a special case for Node 8 in you appveyor config. But we run `npm test` unconditionally in citgm

**Comment by mcollina** [comment]
Ah, yes now I remember: this is the issue.

https://github.com/davidmarkclements/0x/issues/188

This goes back to https://github.com/tapjs/spawn-wrap monkeypatching some internals. It breaks on Node 8, but it works fine on Node 10.

**Pull request merged**
