### PR TITLE
bin: add citgm-all

### PR DESCRIPTION
**Pull request by TheAlphaNerd**
This PR adds a new bin to the project ```citgm-all```

By default ```citgm-all``` will run the test suite of every package in the lookup table. If a custom lookup table is provided it will iterate across that instead.

TODO:
- [ ] add more modules to the lookup table
- [x] ~~ensure every package in lookup works(ish)~~
- [ ] #26 needs to land
- [ ] discuss running in parallel instead of series
- [ ] a potential memory leak has been exposed
- [ ] update documentation

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
This is the current output I'm going to examine each module

error:   failed modules      |
error:   [
error:     {
error:       "name": "express",
error:       "err": "The canary is dead."
error:     },
error:     {
error:       "name": "chalk",
error:       "err": "The canary is dead."
error:     },
error:     {
error:       "name": "colors",
error:       "err": "The canary is dead."
error:     },
error:     {
error:       "name": "bluebird",
error:       "err": "The canary is dead."
error:     },
error:     {
error:       "name": "yeoman-generator",
error:       "err": "Install Failed"
error:     },
error:     {
error:       "name": "redis",
error:       "err": "No project downloaded"
error:     },
error:     {
error:       "name": "jquery",
error:       "err": "The canary is dead."
error:     },
error:     {
error:       "name": "handlebars",
error:       "err": "The canary is dead."
error:     },
error:     {
error:       "name": "yosay",
error:       "err": "The canary is dead."
error:     },
error:     {
error:       "name": "mime",
error:       "err": "The canary is dead."
error:     },
error:     {
error:       "name": "mongodb",
error:       "err": "No project downloaded"
error:     }
error:   ]

**Comment by jasnell** [comment]
woo! awesome

**Comment by TheAlphaNerd** [comment]
reopening

**Pull request closed without merging**
