### PR TITLE
lookup: vinyl-fs flaky on WIN only

### PR DESCRIPTION
**Pull request by al-k21**
Refs: https://github.com/nodejs/citgm/issues/537

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by MylesBorins** [comment]
s/vinil/vinyl

Do we have tests to prove it is no longer flaky?

**Comment by mcollina** [comment]
If this is the problem we talked about @MylesBorins, it was solved in https://github.com/gulpjs/vinyl-fs/pull/296.

**Comment by MylesBorins** [comment]
It has been flaky on various versions before that problem was fixed. So
just would like to ensure this is fixed on 4 / 6 / 8 / 9 / master before
removing flaky

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/15/console

**Comment by al-k21** [comment]
Seems like it's still fails across all the platforms:

```sh
10:22:02 error:                     | 223 passing (25s)                                                                                                                                            
10:22:02 error:                     | 18 pending                                                                                                                                                   
10:22:02 error:                     | 1 failing                                                                                                                                                    
10:22:02 error:                     |                                                                                                                                                              
10:22:02 error:                     | 1) .dest() with custom owner calls fchown when the uid and/or gid are provided on the vinyl stat:                                                            
10:22:02 error:                     |                                                                                                                                                              
10:22:02 error:                     | Uncaught Error: Expected 0 to equal 1                                                                                                                        
10:22:02 error:                     | + expected - actual                                                                                                                                          
10:22:02 error:                     |                                                                                                                                                              
10:22:02 error:                     | -0                                                                                                                                                           
10:22:02 error:                     | +1                                                                                                                                                           
10:22:02 error:                     |                                                                                                                                                              
10:22:02 error:                     | at assert (node_modules/expect/lib/assert.js:29:9)                                                                                                           
10:22:02 error:                     | at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)                                                                                        
10:22:02 error:                     | at assert (test/dest-owner.js:49:38)                                                                                                                         
10:22:02 error:                     | at ConcatStream.<anonymous> (node_modules/concat-stream/index.js:36:43)                                                                                      
10:22:02 error:                     | at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:14)                                                                                 
10:22:02 error:                     | at endWritable (node_modules/readable-stream/lib/_stream_writable.js:628:3)                                                                                  
10:22:02 error:                     | at ConcatStream.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:584:41)                                                                   
10:22:02 error:                     | at Pumpify.onend (node_modules/readable-stream/lib/_stream_readable.js:577:10)                                                                               
10:22:02 error:                     | at endReadableNT (node_modules/readable-stream/lib/_stream_readable.js:1000:12)                                                                              
10:22:02 error:                     | at _combinedTickCallback (internal/process/next_tick.js:80:11)                                                                                               
10:22:02 error:                     | at process._tickCallback (internal/process/next_tick.js:104:9)                                                                                               
10:22:02 error:                     |                                                                                                                                                              
10:22:02 error:                     |                                                                                                                                                              
10:22:02 error:                     |                                                                                                                                                              
10:22:02 error:                     |                                                                                                                                                              
10:22:02 error:                     | npm ERR! Test failed.  See above for more details.                                                                                                           
10:22:02 error: done                | The smoke test has failed.
```

This will be investigated in https://github.com/nodejs/citgm/issues/537.
Added to the https://github.com/nodejs/citgm/projects/1. 
Closing for now, feel free to reopen.

**Pull request closed without merging**
