### PR TITLE
lookup: add lru-cache

### PR DESCRIPTION
**Pull request by pacostas**
## Description
This PR adds `lru-cache` module on `/lib/lookup.json`

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/HEAD/CONTRIBUTING.md)

##### Hard Requirements
- [x] Module source code must be on Github.
- [x] Published versions must include a tag on Github
- [x] The test process must be executable with only the commands npm install && npm test or (yarn install && yarn test) - using the tarball downloaded from the Github tag mentioned above
- [x] The tests pass on supported major release lines
- [x] The maintainers of the module remain responsive when there are problems
- [x] At least one module maintainer must be added to the lookup maintainers field

##### Soft Requirements
At least one of:

- [x] The module must be actively used by the community OR
- [ ] The module must be heavily depended on OR
- [ ] The module must cover unique portions of our API OR
- [x] The module fits into a key category (e.g. Testing, Streams, Monitoring, etc.) OR
- [ ] The module is under the Node.js foundation Github org OR
- [ ] The module is identified as an important module by a Node.js Working Group

### CODE REVIEW

**Comment by pacostas** [comment]
Opened Issue: https://github.com/isaacs/node-lru-cache/issues/260

**Comment by pacostas** [comment]
I've set as flaky on windows due to this issue occurs while running the tests: https://github.com/nodejs/citgm/issues/930

**Comment by pacostas** [comment]
Changed it to skip due to the tests for windows still run for flaky and block the pr

**Comment by BethGriggs** [comment]
CITGM pipeline run: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/220/

**Comment by BethGriggs** [comment]
CITGM Pipeline run 2: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/221/

**Comment by BethGriggs** [comment]
New CITGM run: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/223/

**Comment by BethGriggs** [comment]
> New CITGM Pipeline run: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/225

These results look good - only error is #917 as expected. :tada:

**Review by BethGriggs — APPROVED** [review]

**Review by richardlau — APPROVED** [review]

**Comment by BethGriggs** [comment]
Merging - the only actions failure in CITGM's test suite is a known flaky windows test which is also flaky on main (#930)

**Pull request merged**
