### PR TITLE
lookup: add "native" tag for native modules

### PR DESCRIPTION
**Pull request by gibfahn**
Fixes: https://github.com/nodejs/citgm/issues/377

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)
- [x] commit message follows commit guidelines

cc/ @richardlau

### CODE REVIEW

**Comment by gibfahn** [comment]
We should build on 7.7.0 with `--exclude-tag native` and make sure it's green.

**Comment by gdams** [comment]
> @gdams We should build on 7.7.0 with --exclude-tag native and make sure it's green.

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/619/

**Comment by gibfahn** [comment]
@MylesBorins I meant that we should run https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild (which was previously called https://ci.nodejs.org/view/Node.js-citgm/job/gibfahn-citgm-smoker-more-platforms). That job fetches from nodejs.org, so it should pick up the failures (I hope).

**Comment by gdams** [comment]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/127/

**Comment by richardlau** [comment]
> That job fetches from nodejs.org, so it should pick up the failures (I hope).

Not if run with --exclude-tag native :smile:

**Comment by gibfahn** [comment]
@richardlau Yeah, `--exclude-tag native` should all pass, `--include-tag native` should all fail...

**Comment by gdams** [comment]
okay so level failed on ppcle & ppcbe but nothing else: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/MACHINE=ppcle-ubuntu1404/127/testReport/%28root%29/citgm/level_v1_6_0/
This is because it has the dependency of leveldown but will only build it if a prebuilt version is not available

**Comment by gdams** [comment]
lets get https://github.com/nodejs/citgm/pull/292 landed and then you can add the native tags to those modules too

**Comment by gibfahn** [comment]
I think we need to think about whether a native module that uses `node-pre-gyp` to download binaries is a native module. Obviously it technically is, but from the point of view of CitGM maybe we need two categories, maybe `native-build` and `native-download` (although that'd be platform specific so difficult to do).

Alternately we could just make sure we specify the `--build-from-source` flag (or the npm config variable) and try to force everything to build from source. We could even try to disable the network while that part of the install is happening.

**Comment by gibfahn** [comment]
@gdams updated

**Comment by gdams** [comment]
@nodejs/citgm can we get some reviews please

**Comment by gibfahn** [comment]
@MylesBorins okay to land this?

**Comment by gibfahn** [comment]
Backported to `v1.x` in https://github.com/nodejs/citgm/commit/2b2e00a6370f77d4eb70b5b160c333ce48b028a0

**Pull request merged**
