### PR TITLE
lookup: don't skip bcrypt for v12

### PR DESCRIPTION
**Pull request by agathver**
Compatible with Node 12 since v3.0.4

##### Checklist

- [x] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [x] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by richardlau** [comment]
CI failed: https://ci.nodejs.org/job/citgm-smoker-nobuild/516/

<details>
<summary>e.g. https://ci.nodejs.org/job/citgm-smoker-nobuild/516/nodes=ubuntu1804-64/console</summary>

```console
18:18:53 verbose: bcrypt npm-install: | make: Entering directory '/home/iojs/build/workspace/citgm-smoker-nobuild/citgm_tmp/7cf4f445-4799-46a1-ad1b-45400b47c576/bcrypt/build'
18:18:53 verbose: bcrypt npm-install: | CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
18:18:53 verbose: bcrypt npm-install: | CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
18:18:53 verbose: bcrypt npm-install: | CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
18:18:54 warn: bcrypt npm-install: | In file included from ../node_modules/nan/nan_converters.h:67:0,                                                                                                                                                                     
18:18:54 warn:                     | from ../node_modules/nan/nan.h:222,                                                                                                                                                                                                  
18:18:54 warn:                     | from ../src/bcrypt_node.cc:1:                                                                                                                                                                                                        
18:18:54 warn:                     | ../node_modules/nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:                                      
18:18:54 warn:                     | ../node_modules/nan/nan_converters_43_inl.h:18:51: warning: ‘v8::MaybeLocal<v8::Boolean> v8::Value::ToBoolean(v8::Local<v8::Context>) const’ is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
18:18:54 warn:                     | val->To ## TYPE(isolate->GetCurrentContext())                            \                                                                                                                                                           
18:18:54 warn:                     | ^                                                                                                                                                                                                                                    
18:18:54 warn:                     | ../node_modules/nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’                                                                                                                                                    
18:18:54 warn:                     | X(Boolean)                                                                                                                                                                                                                           
18:18:54 warn:                     | ^                                                                                                                                                                                                                                    
18:18:54 warn:                     | In file included from /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/v8-internal.h:13:0,                                                                                                                         
18:18:54 warn:                     | from /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/v8.h:25,                                                                                                                                                     
18:18:54 warn:                     | from /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/node.h:63,                                                                                                                                                   
18:18:54 warn:                     | from ../node_modules/nan/nan.h:53,                                                                                                                                                                                                   
18:18:54 warn:                     | from ../src/bcrypt_node.cc:1:                                                                                                                                                                                                        
18:18:54 warn:                     | /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/v8.h:2398:63: note: declared here                                                                                                                                 
18:18:54 warn:                     | V8_WARN_UNUSED_RESULT MaybeLocal<Boolean> ToBoolean(                                                                                                                                                                                 
18:18:54 warn:                     | ^                                                                                                                                                                                                                                    
18:18:54 warn:                     | /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/v8config.h:341:3: note: in definition of macro ‘V8_DEPRECATE_SOON’                                                                                                
18:18:54 warn:                     | declarator __attribute__((deprecated(message)))                                                                                                                                                                                      
18:18:54 warn:                     | ^~~~~~~~~~                                                                                                                                                                                                                           
18:18:54 warn:                     | In file included from ../node_modules/nan/nan_converters.h:67:0,                                                                                                                                                                     
18:18:54 warn:                     | from ../node_modules/nan/nan.h:222,                                                                                                                                                                                                  
18:18:54 warn:                     | from ../src/bcrypt_node.cc:1:                                                                                                                                                                                                        
18:18:54 warn:                     | ../node_modules/nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)’:                                                 
18:18:54 warn:                     | ../node_modules/nan/nan_converters_43_inl.h:37:57: warning: ‘v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const’ is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]    
18:18:54 warn:                     | return val->NAME ## Value(isolate->GetCurrentContext());                     \                                                                                                                                                       
18:18:54 warn:                     | ^                                                                                                                                                                                                                                    
18:18:54 warn:                     | ../node_modules/nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’                                                                                                                                                    
18:18:54 warn:                     | X(bool, Boolean)                                                                                                                                                                                                                     
18:18:54 warn:                     | ^                                                                                                                                                                                                                                    
18:18:54 warn:                     | In file included from /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/v8-internal.h:13:0,                                                                                                                         
18:18:54 warn:                     | from /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/v8.h:25,                                                                                                                                                     
18:18:54 warn:                     | from /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/node.h:63,                                                                                                                                                   
18:18:54 warn:                     | from ../node_modules/nan/nan.h:53,                                                                                                                                                                                                   
18:18:54 warn:                     | from ../src/bcrypt_node.cc:1:                                                                                                                                                                                                        
18:18:54 warn:                     | /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/v8.h:2436:55: note: declared here                                                                                                                                 
18:18:54 warn:                     | V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(                                                                                                                                                                                      
18:18:54 warn:                     | ^                                                                                                                                                                                                                                    
18:18:54 warn:                     | /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/v8config.h:341:3: note: in definition of macro ‘V8_DEPRECATE_SOON’                                                                                                
18:18:54 warn:                     | declarator __attribute__((deprecated(message)))                                                                                                                                                                                      
18:18:54 warn:                     | ^~~~~~~~~~                                                                                                                                                                                                                           
18:18:54 warn:                     | In file included from ../node_modules/nan/nan_new.h:189:0,                                                                                                                                                                           
18:18:54 warn:                     | from ../node_modules/nan/nan.h:223,                                                                                                                                                                                                  
18:18:54 warn:                     | from ../src/bcrypt_node.cc:1:                                                                                                                                                                                                        
18:18:54 warn:                     | ../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:                               
18:18:54 warn:                     | ../node_modules/nan/nan_implementation_12_inl.h:356:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’                                                                                      
18:18:54 warn:                     | return v8::StringObject::New(value).As<v8::StringObject>();                                                                                                                                                                          
18:18:54 warn:                     | ^                                                                                                                                                                                                                                    
18:18:54 warn:                     | In file included from /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/node.h:63:0,                                                                                                                                
18:18:54 warn:                     | from ../node_modules/nan/nan.h:53,                                                                                                                                                                                                   
18:18:54 warn:                     | from ../src/bcrypt_node.cc:1:                                                                                                                                                                                                        
18:18:54 warn:                     | /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/v8.h:5131:23: note: candidate: static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)                                             
18:18:54 warn:                     | static Local<Value> New(Isolate* isolate, Local<String> value);                                                                                                                                                                      
18:18:54 warn:                     | ^~~                                                                                                                                                                                                                                  
18:18:54 warn:                     | /home/iojs/.node-gyp/12.0.0-nightly20190314107c95da0d/include/node/v8.h:5131:23: note:   candidate expects 2 arguments, 1 provided                                                                                                   
18:18:54 warn:                     | In file included from ../node_modules/nan/nan_new.h:189:0,                                                                                                                                                                           
18:18:54 warn:                     | from ../node_modules/nan/nan.h:223,                                                                                                                                                                                                  
18:18:54 warn:                     | from ../src/bcrypt_node.cc:1:                                                                                                                                                                                                        
18:18:54 warn:                     | ../node_modules/nan/nan_implementation_12_inl.h:356:58: error: expected primary-expression before ‘>’ token                                                                                                                          
18:18:54 warn:                     | return v8::StringObject::New(value).As<v8::StringObject>();                                                                                                                                                                          
18:18:54 warn:                     | ^                                                                                                                                                                                                                                    
18:18:54 warn:                     | ../node_modules/nan/nan_implementation_12_inl.h:356:60: error: expected primary-expression before ‘)’ token                                                                                                                          
18:18:54 warn:                     | return v8::StringObject::New(value).As<v8::StringObject>();                                                                                                                                                                          
18:18:54 warn:                     | ^                                                                                                                                                                                                                                    
18:18:54 warn: bcrypt npm-install: | make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
18:18:54 warn:                     | gyp ERR! build error                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
18:18:54 warn:                     | gyp ERR! stack Error: `make` failed with exit code: 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
18:18:54 warn:                     | gyp ERR! stack     at ChildProcess.onExit (/home/iojs/build/workspace/citgm-smoker-nobuild/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
18:18:54 warn:                     | gyp ERR! stack     at ChildProcess.emit (events.js:198:13)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
18:18:54 warn:                     | gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
18:18:54 warn:                     | gyp ERR! System Linux 4.15.0-39-generic                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
18:18:54 warn:                     | gyp ERR! command "/home/iojs/build/workspace/citgm-smoker-nobuild/node/bin/node" "/home/iojs/build/workspace/citgm-smoker-nobuild/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/iojs/build/workspace/citgm-smoker-nobuild/citgm_tmp/7cf4f445-4799-46a1-ad1b-45400b47c576/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/iojs/build/workspace/citgm-smoker-nobuild/citgm_tmp/7cf4f445-4799-46a1-ad1b-45400b47c576/bcrypt/lib/binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v68"                
18:18:54 warn:                     | gyp ERR! cwd /home/iojs/build/workspace/citgm-smoker-nobuild/citgm_tmp/7cf4f445-4799-46a1-ad1b-45400b47c576/bcrypt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
18:18:54 warn:                     | gyp ERR! node -v v12.0.0-nightly20190314107c95da0d                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
18:18:54 warn:                     | gyp ERR! node-gyp -v v3.8.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
18:18:54 warn:                     | gyp ERR! not ok                  
```
</details>

It looks like bcrypt has fixed the version of nan at 2.12.1 (https://github.com/kelektiv/node.bcrypt.js/blob/f725979af34e5ed8ef86f92db525678560acb4c2/package.json#L32) but the first version of nan to be compatible with Node.js master (to be 12) is 2.13.0.

**Comment by agathver** [comment]
Looks like the version was released 2 days ago. We would need to release a new version based on it.

**Comment by agathver** [comment]
@richardlau v3.0.5 is out with updated NAN. Can you re-trigger the build?

**Comment by richardlau** [comment]
New CI: https://ci.nodejs.org/job/citgm-smoker-nobuild/540/

**Comment by MylesBorins** [comment]
windows failure is odd

**Comment by BridgeAR** [comment]
One more rebuild with the latest nightly: https://ci.nodejs.org/job/citgm-smoker-nobuild/545/

**Comment by agathver** [comment]
@BridgeAR the Windows box is having some connectivity issues. Its consistently failing during git clone also in other builds.

**Pull request merged**
