### PR TITLE
bump to v2.0.0-beta

### PR DESCRIPTION
**Pull request by MylesBorins**
we should bump the version on master

### CODE REVIEW

**Comment by refack** [comment]
there is a dedicated field in package.json
```json
  "publishConfig": {
    "tag": "beta"
  },
```
Allows you to be "semver independent"
Ref: https://docs.npmjs.com/getting-started/using-tags

**Comment by MylesBorins** [comment]
Based on how npm themselves are handling their beta I have updated this PR

https://github.com/npm/npm/blob/release-beta-5/package.json#L2

**Comment by MylesBorins** [comment]
LOL no need for beta we release 2.0.0 
¯\\\_(ツ)\_/¯

**Pull request closed without merging**
