### PR TITLE
add prom-client to lookup

### LINKED ISSUE #860: Add prom-client to the lookup
See https://github.com/siimon/prom-client/pull/436 and https://github.com/nodejs/node/issues/38412

### PR DESCRIPTION
**Pull request by SimenB**
Fixes #860

@siimon @zbjornson do you want to not be included here?

Note that `16.x` on GH Actions will fail: https://github.com/siimon/prom-client/pull/436#issuecomment-832452127

##### Checklist

- [x] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/HEAD/CONTRIBUTING.md)

### CODE REVIEW

**Comment by targos** [comment]
https://github.com/nodejs/citgm/actions/runs/812506546

**Comment by SimenB** [comment]
> [nodejs/citgm/actions/runs/812506546](https://github.com/nodejs/citgm/actions/runs/812506546)

Super weird Windows is failing... It passes on our own CI.

And as I type this the second commit works (installed with npm as that's what we use), so.... 🤷 😅

**Comment by targos** [comment]
> wait no, the status reported in this PR is different than that link 😬

Yeah, that link is a manual run of `citgm prom-client` on various platforms and Node.js versions.

**Comment by targos** [comment]
I just re-ran it to test without yarn: https://github.com/nodejs/citgm/actions/runs/812506546

**Comment by SimenB** [comment]
I do _not_ understand the windows failure. The function call it's complaining that's missing is right above, and as mentioned it works in our own CI running windows

**Comment by targos** [comment]
I tried on my local Windows machine:
- download zip manually
- extract
- npm i
- npm t
It works (node 14)

**Comment by targos** [comment]
```
> citgm prom-client
info:    starting            | prom-client
info:    lookup              | prom-client
info:    lookup-notfound     | prom-client
info:    lookup-githead      | https://github.com/siimon/prom-client/archive/e29a1721f442973eb733cafedb2ed6de82b0c7e5.tar.gz
info:    prom-client npm:    | Downloading project: https://github.com/siimon/prom-client/archive/e29a1721f442973eb733cafedb2ed6de82b0c7e5.tar.gz
info:    prom-client npm:    | Project downloaded prom-client-13.1.0.tgz
info:    prom-client npm:    | npm install started
info:    prom-client npm:    | npm install successfully completed
info:    prom-client npm:    | test suite started
info:    passing module(s)   |
info:    module name:        | prom-client
info:    version:            | 13.1.0
info:    done                | The smoke test has passed.
info:    duration            | test duration: 125168ms
```

**Comment by targos** [comment]
So the failure seems specific to GitHub Actions. Let me run it on our CI (it's what will be used for Node.js releases anyway): https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/145/console

**Comment by SimenB** [comment]
Cool 👍 We use GH Actions as well, so this is quite mysterious

**Review by mhdawson — APPROVED** [review]
LGTM once CI issues are resolved, will be great to have CITGM coverage for this package.

**Comment by SimenB** [comment]
> So the failure seems specific to GitHub Actions. Let me run it on our CI (it's what will be used for Node.js releases anyway): [ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/145/console](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/145/console)

I'm unable to properly read this, but it seems it passed on most arches/OSes, but failed on some, and the failures are either errors from `make` or mismatching python versions which doesn't seem related? Again, I don't really know how to navigate Jenkins (never used it beyond this repo 😅) so the probability I'm missing something is quite high

**Comment by targos** [comment]
New run: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/146/

**Review by targos — APPROVED** [review]

**Pull request merged**
