### PR TITLE
lookup: unskip zeromq

### PR DESCRIPTION
**Pull request by targos**
I'm opening this to try it on our CI but I'm not sure it will work, because zeromq depends on CMake: https://github.com/zeromq/zeromq.js#building-from-source

### CODE REVIEW

**Comment by targos** [comment]
Actions CI: https://github.com/targos/citgm/actions/runs/627134439
Node CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/138/

**Comment by richardlau** [comment]
FWIW we do have cmake on a lot of platforms in the CI now. It’s used  in the libuv builds.

**Comment by targos** [comment]
It fails everywhere, and not only because of missing cmake... I'll keep this open in case someone wants to look into it.

**Comment by MylesBorins** [comment]
Hey all, I made a boo boo on main and had to force push. I've rebased this branch and force pushed to make sure that you don't have to do extra work because of my mistake

**Review by favelado-web — APPROVED** [review]

**Pull request closed without merging**
