### PR TITLE
WIP getting to 100% (ish) code coverage

### PR DESCRIPTION
**Pull request by TheAlphaNerd**
This PR is going to track getting 100% code coverage on the different systems of citgm.

 - [ ] `lib/`
 - [ ] `lib/npm`
 - [x] `lib/reporter` ✨ 100% ✨
 - [x] `bin/` 87% - 100%
    * cannot get 100% without major refactor due to how we handle checking for windows

This PR will likely modify parts of the citgm lib / bin directories as inconsistencies are found, but the intention is that this should be a semver patch update

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
Coverage on master

screen shot 2016-02-29 at 5 27 40 pm

current coverage in this PR as of https://github.com/TheAlphaNerd/citgm/commit/4aa268612f656f6155ce9593f6cecdd0fcacd388

screen shot 2016-02-29 at 5 28 21 pm

**Comment by TheAlphaNerd** [comment]
Did a bunch of work on lib today... current status

screen shot 2016-03-04 at 3 58 24 pm

**Comment by jasnell** [comment]
LGTM

**Comment by TheAlphaNerd** [comment]
Ok... I think this is where I'm going to call it 

All coverage types are over 90%, and pretty much everything we are missing is either `child_process` error handling, cross platform specifics, and a handful of edges in if statements.

screen shot 2016-03-22 at 1 58 47 pm

**Pull request merged**
