### PR TITLE
chore: test using node 16, remove node 10

### PR DESCRIPTION
**Pull request by SimenB**
10 is EOL, and 16 is new and shiny? 😀 

Possibly blocked by #852?

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/HEAD/CONTRIBUTING.md)

### CODE REVIEW

**Review by targos — APPROVED** [review]

**Comment by targos** [comment]
Change LGTM but we need to understand why it fails on v16 and fix that

**Comment by targos** [comment]
> Possibly blocked by #852?

No, that's something else. #852 is about failures of `citgm-all` runs, not CITGM's own tests.

**Comment by targos** [comment]
One of the errors is:
image


/cc @MylesBorins could it be a breaking change from npm v7 ?

**Review by richardlau — APPROVED** [review]

**Review by Trott — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by MylesBorins** [comment]
@targos I'm getting an even earlier failure with v16.1.0 😅

```
> tap -J --timeout 480 "test/**/test-*.js"

Error: Cannot find module './reports/base'
Require stack:
- /Users/mylesborins/code/citgm/node_modules/jackspeak/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at resolveFileName (/Users/mylesborins/code/citgm/node_modules/tap/node_modules/resolve-from/index.js:17:39)
    at resolveFrom (/Users/mylesborins/code/citgm/node_modules/tap/node_modules/resolve-from/index.js:31:9)
    at module.exports (/Users/mylesborins/code/citgm/node_modules/tap/node_modules/resolve-from/index.js:34:41)
    at importJSX (/Users/mylesborins/code/citgm/node_modules/tap/node_modules/import-jsx/index.js:24:21)
    at module.exports (/Users/mylesborins/code/citgm/node_modules/tap/node_modules/treport/lib/index.js:13:18)
    at exports.makeReporter (/Users/mylesborins/code/citgm/node_modules/tap/bin/run.js:422:23)
    at runTests (/Users/mylesborins/code/citgm/node_modules/tap/bin/run.js:744:3)
    at mainAsync (/Users/mylesborins/code/citgm/node_modules/tap/bin/run.js:244:5)
    at main (/Users/mylesborins/code/citgm/node_modules/tap/bin/run.js:127:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/mylesborins/code/citgm/node_modules/jackspeak/noop.js' ]
}
```

**Comment by BethGriggs** [comment]
@MylesBorins  that error looks similar to https://github.com/tapjs/node-tap/issues/624#issuecomment-823209712 / https://github.com/tapjs/node-tap/issues/746

**Comment by MylesBorins** [comment]
hmmm maybe we need to update tap in CITGM?

**Comment by MylesBorins** [comment]
I have a reproduction for the npm team and we've found where this regressed. Hopefully a fix won't be terribly difficult

**Comment by wraithgar** [comment]
This was only working by coincidence pre-7.8.0.  Based on how it was "working" before, we may want to think about running commands from a `cwd` that does not contain a package.

**Comment by targos** [comment]
Given the results in https://github.com/nodejs/citgm/pull/866, npm is fixed so I'm landing this PR.

**Pull request merged**
