### PR TITLE
doc: add collaboration policy

### PR DESCRIPTION
**Pull request by TheAlphaNerd**
first pass, expecting to make changes

### CODE REVIEW

**Comment by jbergstroem** [comment]
LGTM!

**Comment by jbergstroem** [comment]
@bengl good point -- this should probably be done in all projects. I'd like to see some 'fallback' to the node.js repo unless sub working groups chooses to lax it and mention what they prefer.

**Comment by bengl** [comment]
Perhaps a reasonable addition would be:

```md
* PRs may be landed by Collaborators using whichever style of merging they deem to be appropriate.
```

That way it's not prescribing, and also not ambiguous.

**Comment by TheAlphaNerd** [comment]
I would add. "as long as there are no merge commits".

I'll update tomorrow

**Comment by TheAlphaNerd** [comment]
Updated, ptal

**Comment by TheAlphaNerd** [comment]
@nodejs/citgm our team is getting bigger and it is important that this document lands ASAP as a contract for us to abide by. Can I get some LGTM's asap please

**Comment by jasnell** [comment]
LGTM

**Comment by TheAlphaNerd** [comment]
landed in 5c91fdc2be

**Pull request closed without merging**
