### PR TITLE
fix: support lookup with semver ranges

### PR DESCRIPTION
**Pull request by targos**
Use the latest satisfying version returned by npm.
Throw an error if nothing matches.

Fixes: https://github.com/nodejs/citgm/issues/762

### CODE REVIEW

**Comment by richardlau** [comment]
So it's easy to miss since Windows Travis tests have been red for a long time, but one of the new tests is failing in Travis on Windows (passes on other platforms): e.g. https://travis-ci.com/nodejs/citgm/jobs/250263800#L826-L856
```
    # Subtest: grab-module-data: semver range

        1..3

        ok 1 - There should be a context.meta

        ok 2 - The name of the results should be omg-i-pass

        not ok 3 - The version should be the latest satisfying the semver range

          ---

          found: 2.0.0

          wanted: 2.0.1

          compare: ===

          at:

            line: 129

            column: 5

            file: test/test-grab-module-data.js

            type: Test

          stack: |

            Test.<anonymous> (test/test-grab-module-data.js:129:5)

          source: |2

              );

              t.equals(

            ----^

                context.meta.version,

                '2.0.1',

          diff: |

            --- wanted

            +++ found

            -2.0.1

            +2.0.0

          ...

        

        # failed 1 of 3 tests

    not ok 5 - grab-module-data: semver range # time=1490.005ms
```

**Comment by targos** [comment]
What? So npm's output is platform-dependant?

**Comment by targos** [comment]
I can reproduce, but I don't understand. On Windows, npm returns only one version instead of an array.

**Comment by targos** [comment]
And it only happens in the test. If I run `npm view --json omg-i-pass@^2.0.0` manually, an array is returned.

**Comment by targos** [comment]
Actually, the real command is `cmd /C npm view --json omg-i-pass@^2.0.0` and with it I effectively get version 2.0.0 only.

**Comment by richardlau** [comment]
> 
> 
> Actually, the real command is `cmd /C npm view --json omg-i-pass@^2.0.0` and with it I effectively get version 2.0.0 only.

Is that all passed as one line? Is this an escaping (the caret) issue?

**Comment by targos** [comment]
It's called like this: `child_process.spawn('cmd', ['npm', 'view', '--json', 'omg-i-pass@^2.0.0'])`

**Comment by targos** [comment]
It's definitely an escaping issue. This is the `process.argv` value in npm-cli.js:
```
[
  'C:\\Users\\targo\\AppData\\Local\\nvs\\default\\node.exe',
  'C:\\Users\\targo\\AppData\\Local\\nvs\\default\\node_modules\\npm\\bin\\npm-cli.js',
  'view',
  '--json',
  'omg-i-pass@2.0.0'
]
```

**Comment by targos** [comment]
Well, the solution is to escape the caret by putting four of them :D

`cmd /C npm view --json omg-i-pass@^^^^2.0.0`

**Pull request merged**
