### PR TITLE
test: fix test-npm-install for npm 5

### PR DESCRIPTION
**Pull request by targos**
The checked error message changed.

##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration/32/

**Comment by gibfahn** [comment]
LGTM if this works on npm4 and npm5

**Comment by targos** [comment]
Quick run to prove it works on npm 4: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration/33/

**Comment by MylesBorins** [comment]
Confirming that this also works on npm@3 (for v6.x)

**Comment by MylesBorins** [comment]
landed in 33073a734f

**Pull request closed without merging**
