### PR TITLE
test the full-icu-test

### PR DESCRIPTION
**Pull request by srl295**
tests `full-icu`

Fixes: https://github.com/nodejs/citgm/issues/142

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
@srl295 why is replace set to false? Should it not be getting the tarball from github rather than npm?

**Comment by TheAlphaNerd** [comment]
@GeorgeAdams95 prefix is only used if replace is set to true. We should 100% have replace set to true, as there are no other modules that are using the npm version. In fact I have considered deprecating replace all together and making it mandatory for the lookup.

**Comment by GeorgeAdams95** [comment]
@TheAlphaNerd, with replace set to true I get the following error: `no-repository-field in package.json`.

**Comment by srl295** [comment]
> Should it not be getting the tarball from github rather than npm?

No, it should be getting it from npm.

**Comment by GeorgeAdams95** [comment]
@srl295 is there a reason for this? do you not have  github repository ?

**Comment by srl295** [comment]
I've fixed the full-icu-test (@1.0.1 )  to have a repo field. if that's
preferred, we can use that mechanism

**Comment by GeorgeAdams95** [comment]
Can you update your pr to have replace:true

**Comment by srl295** [comment]
done PTAL

**Comment by TheAlphaNerd** [comment]
@GeorgeAdams95 there is indeed a prefix in the released tarball on github. I would also prefer to not use master.

https://github.com/unicode-org/full-icu-test/releases

@srl295 likely a good idea to do a tag when you do a new release, this is how github generates the tarballs. I am a big fan of `semver-sync` to automate the process of cutting a version with a tag + bumping the package.json.

@srl295 as an aside there is currently a conflict in this update, can you please rebase against master

**Comment by GeorgeAdams95** [comment]
LGTM if rebased against master

**Comment by srl295** [comment]
sorry, multitasking here.   I did tag since the above. and rebased.

```
$ node ./bin/citgm.js full-icu-test
info:    starting            | full-icu-test       
info:    npm:                | Downloading project: https://github.com/unicode-org/full-icu-test/archive/v1.0.1.tar.gz
info:    npm:                | Project downloaded full-icu-test-1.0.1.tgz
info:    npm:                | install started     
info:    npm:                | install successfully completed
info:    npm:                | test suite started  
info:    passing module(s)   |                     
info:    module name:        | full-icu-test       
info:    version:            | 1.0.1               
info:    done                | The smoke test has passed.
```

**Comment by TheAlphaNerd** [comment]
here's a run on citgm to test falkyness

master: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/439/
v7: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/440/
v6: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/441/
v4: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/442/

**Comment by GeorgeAdams95** [comment]
landed in https://github.com/nodejs/citgm/commit/5a56f197f22fa91ecc3f225968062df220b43338

**Pull request closed without merging**
