### PR TITLE
docs: clean up top level documents

### PR DESCRIPTION
**Pull request by TheAlphaNerd**
Removed ```SIGNED.md``` which is not currently active or correct

Added Code of Conduct and Moderation policy
  * forwards to Node.js CoC and Moderation Policy

### CODE REVIEW

**Comment by jasnell** [comment]
LGTM

**Comment by jasnell** [comment]
You might want to update the AUTHORS file too

**Comment by TheAlphaNerd** [comment]
landed in 68ea7f3667462e6dd769d22a420e1847f067b6c1

**Pull request closed without merging**
