### PR TITLE
lookup: unskip and unflaky some modules

### PR DESCRIPTION
**Pull request by targos**
Based on local testing (Linux)

### CODE REVIEW

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/79/console

**Comment by targos** [comment]
@not-an-aardvark is there a way to skip browser tests in ESLint?

**Comment by not-an-aardvark** [comment]
Not as far as I'm aware, although I'd be open to adding that. Is the issue that CITGM is running on some environments that don't support headless chrome?

**Comment by targos** [comment]
@not-an-aardvark yes, libX11 is not installed in our CI machines.

**Comment by targos** [comment]
I've skipped ESLint again for now and made some changes based on CI results.

New CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/80/

@BridgeAR @richardlau PTAL. I introduced an new "comment" field in the lookup to explain why some modules are skipped or flaky. We could use its value later in the logs.

**Comment by richardlau** [comment]
> @BridgeAR @richardlau PTAL. I introduced an new "comment" field in the lookup to explain why some modules are skipped or flaky. We could use its value later in the logs.

Have you changed your mind over https://github.com/nodejs/citgm/issues/547#issuecomment-368040724 then? 😁 

We can log the comment value in the junit output so that it appears in the Jenkins results. I can submit a PR for this after this lands.

**Comment by targos** [comment]
> Have you changed your mind over #547 (comment) then? 😁

Yes, I have to admit, the "project" approach didn't work so well ^^.

**Comment by BridgeAR** [comment]
@richardlau 
> We can log the comment value in the junit output so that it appears in the Jenkins results. I can submit a PR for this after this lands.

I like that idea. That would indeed be valuable to know.

**Comment by targos** [comment]
watchify failed a lot on windows. i'll skip it on that platform before landing

**Pull request merged**
