### PR TITLE
lookup: add jose

### PR DESCRIPTION
**Pull request by panva**
adds [`jose`](https://www.npmjs.com/package/jose)

It covers the `node:crypto`, and `Web Cryptography API` modules.

### CODE REVIEW

**Comment by panva** [comment]
May need a skip on `fips` if we any fips citgm runs in place? I'm not sure.

**Comment by panva** [comment]
cc @mhdawson

**Comment by panva** [comment]
# Hard Requirements
- [x] Module source code must be on Github.
- [x] Published versions must include a tag on Github
- [x] The test process must be executable with only the commands npm install && npm test (actually two unique test suites using the different crypto modules are present)
- [x] The tests pass on supported major release lines
- [x] The maintainers of the module remain responsive when there are problems
- [x] At least one module maintainer must be added to the lookup maintainers field

# Soft Requirements

- [x] The module must be actively used by the community
- [x] The module must be heavily depended on
- [x] The module must cover unique portions of our API (crypto, webcrypto)
- [x] The module fits into a key category (crypto)
- [ ] The module is under the Node.js foundation Github org
- [ ] The module is identified as an important module by a Node.js Working Group
Procedure

**Comment by panva** [comment]
@targos is there a CITGM specific environment variable based on which I could disable flaky network tests?

**Comment by targos** [comment]
I'm not sure, but in any case, you can add the env variables of your choice in the lookup like here: https://github.com/nodejs/citgm/blob/a35b3fd33f38cf3589f5fa29fd082fbe3c5f153f/lib/lookup.json#L254

**Comment by panva** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/205/

**Comment by mhdawson** [comment]
I believe this is related to openid support and I believe that it's good/important that we have coverage of that area in CITGM. It would be also be great to add https://www.npmjs.com/package/openid-client as well.

**Comment by mhdawson** [comment]
I don't think we run CITGM on fips @richardlau can you fact check me on that?

**Review by mhdawson — APPROVED** [review]
LGTM, agree that the failures don't look related.

**Comment by mhdawson** [comment]
In respect to 
>would be also be great to add https://www.npmjs.com/package/openid-client as well.

I see that already happened, so nevermind :)

**Comment by panva** [comment]
> actually I see the PR was closed without landing. @panva was that so you could get jose in first?

I need to update the test runner to something more flexible and predictable. So it's coming, eventually.

**Comment by mhdawson** [comment]
> I need to update the test runner to something more flexible and predictable. So it's coming, eventually.

Thanks, good to know.

**Comment by richardlau** [comment]
> I don't think we run CITGM on fips @richardlau can you fact check me on that?

We do not.

IBM did add some `"expectFail": "fips"` entries in `lookup.json`, e.g.
https://github.com/nodejs/citgm/blob/a35b3fd33f38cf3589f5fa29fd082fbe3c5f153f/lib/lookup.json#L58 for when they were internally running CITGM in a fips configuration, but I believe that stopped when Node.js moved to OpenSSL 1.1.1 where there was no upstream fips support.

**Comment by mhdawson** [comment]
@richardlau so it would be good to add `"expectFail": "fips", ` in this PR for jose to handle a future where we might do fips testing again, right?

**Comment by panva** [comment]
> @richardlau so it would be good to add `"expectFail": "fips", ` in this PR for jose to handle a future where we might do fips testing again, right?

Who's to know without actually having a build? It may fail because of `expectFail` and the suite being fine, it might as well fail because of the opposite reason.

When we have a fips build we'll deal with it.

**Comment by mhdawson** [comment]
@panva that works for me :)

**Comment by richardlau** [comment]
> @richardlau so it would be good to add `"expectFail": "fips", ` in this PR for jose to handle a future where we might do fips testing again, right?

I'm inclined to agree with @panva and ignore it until it becomes an issue. I don't see much benefit for running CITGM against a FIPS enabled Node.js on a regular basis -- a lot of modules are going to fail for using (or using a dependency that is using) algorithms like md5 to do hashing, which is totally reasonable but not an algorithm permitted by FIPS.

**Comment by panva** [comment]
This is good to go now, i've even expanded the tests.

- [14](https://ci.nodejs.org/job/citgm-smoker-nobuild/1469/)
- [16](https://ci.nodejs.org/job/citgm-smoker-nobuild/1470/)
- [18](https://ci.nodejs.org/job/citgm-smoker-nobuild/1471/)
- [19](https://ci.nodejs.org/job/citgm-smoker-nobuild/1472/)

The remaining failures are fetch timeout related and these will go away with the next tagged release, I just don't have anything of substance to release right now.

**Comment by panva** [comment]
This is good to go now, i've even expanded the tests.

- [14](https://ci.nodejs.org/job/citgm-smoker-nobuild/1477/)
- [16](https://ci.nodejs.org/job/citgm-smoker-nobuild/1478/)
- [18](https://ci.nodejs.org/job/citgm-smoker-nobuild/1479/)
- [19](https://ci.nodejs.org/job/citgm-smoker-nobuild/1480/)

**Review by richardlau — APPROVED** [review]

**Comment by panva** [comment]
@richardlau @mhdawson Is this good to land then?

**Comment by mhdawson** [comment]
I'd like @richardlau's confirmation as I think he's been more active in the citgm repo.

**Comment by richardlau** [comment]
> I'd like @richardlau's confirmation as I think he's been more active in the citgm repo.

I approved this. It LGTM.

**Comment by mhdawson** [comment]
Landed, @panva thanks for your work on this.

**Comment by panva** [comment]
Thank you!

**Pull request merged**
