### PR TITLE
lookup: add new modules

### PR DESCRIPTION
**Pull request by gdams**
Adding some new modules discussed in https://github.com/nodejs/citgm/issues/127

### CODE REVIEW

**Comment by MylesBorins** [comment]
@gdams have you tested these? I the citgm run on them are clean I'm positive with this landing

**Comment by gdams** [comment]
@MylesBorins this is clean on IBM jenkins but will need a run in the smoker job to confirm

**Comment by gdams** [comment]
master: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/513/console

**Comment by MylesBorins** [comment]
@gdams is this Pr now updated with appropriate flakyness? If so LGTM

**Comment by MylesBorins** [comment]
@gdams is there anything blocking this?

**Comment by MylesBorins** [comment]
@gdams can you please rebase and add maintainers please

**Comment by gdams** [comment]
@MylesBorins updated PTAL

**Comment by MylesBorins** [comment]
landed in b88c177458

**Pull request closed without merging**
