### PR TITLE
fix: always set the YARN_IGNORE_ENGINES env variable

### PR DESCRIPTION
**Pull request by targos**
Fixes: https://github.com/nodejs/citgm/issues/737

### CODE REVIEW

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1849/

**Comment by richardlau** [comment]
https://github.com/nodejs/citgm/blob/be3c299f0aaa71f42e9fb9ce652881354a3743b4/test/test-create-options.js#L24-L46 will probably need to be changed.

**Comment by targos** [comment]
thanks @richardlau, it's fixed.

**Comment by targos** [comment]
CI with `nodejs/node#master` passed:
```
20:01:49 ++ citgm-all -J --includeTags eslint-plugin-jest pug --nodedir=/home/iojs/build/workspace/citgm-smoker/nodes/fedora-last-latest-x64/node -v warn -x /home/iojs/build/workspace/citgm-smoker/nodes/fedora-last-latest-x64/smoker/report.xml -q error --tmpDir /home/iojs/build/workspace/citgm-smoker/nodes/fedora-last-latest-x64/citgm_tmp
20:01:55 warn: eslint-plugin-jest yarn-install:| warning You are using Node "13.0.0-pre" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
20:01:57 warn: pug yarn-install:   | warning You are using Node "13.0.0-pre" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
20:01:57 warn: eslint-plugin-jest yarn-install:| warning "jest > jest-cli > @jest/core > jest-resolve-dependencies@24.4.0" has unmet peer dependency "jest-resolve@^24.1.0".
20:01:57 warn: eslint-plugin-jest yarn-install:| warning "jest > jest-cli > jest-config > jest-resolve@24.4.0" has unmet peer dependency "jest-haste-map@^24.0.0".
20:02:33 Regular expression run condition: Expression=[Windows_NT], Label=[]
20:02:33 Run condition [Regular expression match] preventing perform for step [BuilderChain]
20:02:33 Performing Post build task...
20:02:33 Match found for : : True
```

**Pull request merged**
