### PR TITLE
lookup: add hapi

### PR DESCRIPTION
**Pull request by gibfahn**
Once this is green we can land it (needs a CI run first).

##### Checklist

- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gibfahn** [comment]
#### Hard Requirements

- [x] Module source code must be on Github.
- [x] Published versions must include a tag on Github
- [x] The test process must be executable with only the commands `npm install && npm test` using the tarball downloaded from the Github tag mentioned above
- [ ] The tests pass on supported major release lines
- [x] The maintainers of the module remain responsive when there are problems
- [x] At least one module maintainer must be added to the lookup maintainers field

#### Soft Requirements

At least one of:
- [x] The module must be actively used by the community
- [x] The module fits into a key category (e.g. Testing, Streams, Monitoring, etc.)

**Comment by gibfahn** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/149/

**Comment by DavidTPate** [comment]
I see that there's a few builds failing on Node 8 which look to be related to the fixes that we have pending in hapijs/hapi#3507 around steams which once those changes land clear up the 3rd failing test for Node 8. Specifically the test `780) transmission transmit() does not leak stream data when request aborts before stream is returned`.

The other two for Node 8 I'm able to reproduce successfully on my machine (Fedora 24) and I'll dig into them further.

As for the failures that we are seeing with some Node 6 tests I'm not able to reproduce them on either of my machines (Fedora 24 and Windows 10). Those will need to be investigated further to see what's amiss.

**Comment by gibfahn** [comment]
Note that this shouldn't be landed until we have green CI runs.

**Comment by hueniverse** [comment]
Note that master had some issues with a recent change that worked on node 8 but broke on 4 and 6. Basically, when calling `res.destroy()` in node 8, the stream `finish` event is fired. Not the case in node 4 and 6 when nothing fires. It is now fixed, but I am pointing it out in case this wasn't expected...

**Comment by mcollina** [comment]
@hueniverse what's the tracking issue of that? I would like to take a look. There was a bug that was fixed in Node 8.1.3 (https://github.com/nodejs/node/pull/13850), and there is another one in zlib that I am going to land this week if no one object (https://github.com/nodejs/node/pull/14330).

**Comment by hueniverse** [comment]
@mcollina https://github.com/hapijs/hapi/issues/2121

**Comment by targos** [comment]
smoke test: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/2/

**Comment by targos** [comment]
Tests are failing on some machines. It seems that `lsof` is not installed everywhere.

```
 Test script errors:
 Multiple callbacks or thrown errors received in test "Connection ext() onPreResponse cleans unused file stream when response is overridden" (done)
       at Immediate.immediate._onImmediate (timers.js:453:18)
       at processImmediate [as _immediateCallback] (timers.js:396:17)
 Multiple callbacks or thrown errors received in test "transmission marshal() closes file handlers when not reading file stream" (done)
       at Immediate.immediate._onImmediate (timers.js:453:18)
       at processImmediate [as _immediateCallback] (timers.js:396:17)
 Multiple callbacks or thrown errors received in test "transmission marshal() closes file handlers when not using a manually open file stream" (done)
       at Immediate.immediate._onImmediate (timers.js:453:18)
       at processImmediate [as _immediateCallback] (timers.js:396:17)
 There were 3 test script error(s).
 Failed tests:
   145) Connection ext() onPreResponse cleans unused file stream when response is overridden:
       spawn lsof ENOENT
       at exports._errnoException (util.js:907:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
       at onErrorNT (internal/child_process.js:363:16)
       at nextTickCallbackWith2Args (node.js:511:9)
       at process._tickDomainCallback (node.js:466:17)
   735) transmission marshal() closes file handlers when not reading file stream:
       spawn lsof ENOENT
       at exports._errnoException (util.js:907:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
       at onErrorNT (internal/child_process.js:363:16)
       at nextTickCallbackWith2Args (node.js:511:9)
       at process._tickDomainCallback (node.js:466:17)
   736) transmission marshal() closes file handlers when not using a manually open file stream:
       spawn lsof ENOENT
       at exports._errnoException (util.js:907:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
       at onErrorNT (internal/child_process.js:363:16)
       at nextTickCallbackWith2Args (node.js:511:9)
       at process._tickDomainCallback (node.js:466:17)
 3 of 916 tests failed
```

**Comment by gibfahn** [comment]
Do the hapi tests require `lsof`?

**Comment by cjihrig** [comment]
Currently, yes. It looks like a few of them spawn it.

**Comment by MylesBorins** [comment]
@nodejs/build are we able to get lsof on host machines?

**Comment by BridgeAR** [comment]
What is the status here?

**Comment by gibfahn** [comment]
>>@nodejs/build are we able to get lsof on host machines?
>What is the status here?

Looks like it needs an issue opening in the build repo to see if we can get `lsof` added.

**Comment by cjihrig** [comment]
I've also opened a PR against hapi to allow the tests to pass when lsof does not exist.

https://github.com/hapijs/hapi/pull/3744

**Comment by apapirovski** [comment]
It seems like this could maybe land given that @cjihrig's patch is in hapi now? Or is there anything else outstanding? Would be nice to have hapi in CitGM.

**Comment by targos** [comment]
CI: https://ci.nodejs.org/blue/organizations/jenkins/citgm-smoker-pipeline/detail/citgm-smoker-pipeline/18/pipeline

**Comment by BridgeAR** [comment]
@targos would you be so kind and start a new CITGM? Seems like it is now outdated.

**Comment by BridgeAR** [comment]
And would someone be so kind and change the title to remove the `WIP`?

**Comment by al-k21** [comment]
CI: https://ci.nodejs.org/job/citgm-smoker-nobuild/MACHINE=ubuntu1204-64/294/console

**Comment by Trott** [comment]
Any reason this hasn't landed? Seems good to go?

**Comment by targos** [comment]
Let's check CI again: https://ci.nodejs.org/blue/organizations/jenkins/citgm-smoker-pipeline/detail/citgm-smoker-pipeline/26/pipeline

**Comment by targos** [comment]
This module must be skipped on v6 because it uses async/await: https://ci.nodejs.org/job/citgm-smoker-nobuild/323/

It also seems a bit flakey and apparently does not support Windows:
https://ci.nodejs.org/job/citgm-smoker-nobuild/324/
https://ci.nodejs.org/job/citgm-smoker-nobuild/325/

**Comment by targos** [comment]
Windows errors from my workstation:

<details>

```
PS C:\Users\targo> citgm hapi
info:    starting            | hapi
info:    lookup              | hapi
info:    lookup-notfound     | hapi
info:    lookup-githead      | https://github.com/hapijs/hapi/archive/76fcd7fa97747c92501b912d64db459d7172cb26.tar.gz
info:    hapi npm:           | Downloading project: https://github.com/hapijs/hapi/archive/76fcd7fa97747c92501b912d64db459d7172cb26.tar.gz
info:    hapi npm:           | Project downloaded hapi-17.5.2.tgz
info:    hapi npm:           | npm install started
warn:    hapi npm-install:   | npm WARN
warn:    hapi npm-install:   | deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warn:    hapi npm-install:   | npm
warn:    hapi npm-install:   | WARN inert@5.1.0 requires a peer of hapi@>=17.0.0 but none is installed. You must install peer dependencies yourself.
warn:                        | npm WARN vision@5.3.3 requires a peer of hapi@17.x.x but none is installed. You must install peer dependencies yourself.
info:    hapi npm:           | npm install successfully completed
info:    hapi npm:           | test suite started
error:   failure             | The canary is dead:
error:   failing module(s)   |
error:   module name:        | hapi
error:   version:            | 17.5.2
error:   error:              | The canary is dead:
error:   error:              | undefinedadded 255 packages from 277 contributors and audited 425 packages in 7.935s                                                                                                                                                            
error:                       | found 0 vulnerabilities                                                                                                                                                                                                                         
error:                       |                                                                                                                                                                                                                                                 
error:                       |                                                                                                                                                                                                                                                 
error:                       | > hapi@17.5.2 test C:\Users\targo\AppData\Local\Temp\64de993b-4b59-41c5-815f-d4fad1b2f077\hapi                                                                                                                                                  
error:                       | > lab -a code -t 100 -L -m 3000                                                                                                                                                                                                                 
error:                       |                                                                                                                                                                                                                                                 
error:                       |                                                                                                                                                                                                                                                 
error:                       |                                                                                                                                                                                                                                                 
error:                       | ..................................................                                                                                                                                                                                              
error:                       | ..............................x....-..............                                                                                                                                                                                              
error:                       | .............xx....x.x............................                                                                                                                                                                                              
error:                       | ...........-......................................                                                                                                                                                                                              
error:                       | ..................................................                                                                                                                                                                                              
error:                       | ..................................................                                                                                                                                                                                              
error:                       | ..............................x...................                                                                                                                                                                                              
error:                       | ..................................................                                                                                                                                                                                              
error:                       | ..................................................                                                                                                                                                                                              
error:                       | ..................................................                                                                                                                                                                                              
error:                       | ..................................................                                                                                                                                                                                              
error:                       | ..................................................                                                                                                                                                                                              
error:                       | ..................................................                                                                                                                                                                                              
error:                       | ..................................................                                                                                                                                                                                              
error:                       | ............--....................................                                                                                                                                                                                              
error:                       | ..................................................                                                                                                                                                                                              
error:                       | ..................................................                                                                                                                                                                                              
error:                       | ..................                                                                                                                                                                                                                              
error:                       |                                                                                                                                                                                                                                                 
error:                       | Failed tests:                                                                                                                                                                                                                                   
error:                       |                                                                                                                                                                                                                                                 
error:                       | 81) Core throws when disabling autoListen and providing special host:                                                                                                                                                                           
error:                       |                                                                                                                                                                                                                                                 
error:                       | actual expected                                                                                                                                                                                                                                 
error:                       |                                                                                                                                                                                                                                                 
error:                       | "InvalidCannot serverspecify optionsport {\nwhen \"autoListen\": is false,\n  \"routes\": {},\n  \"port\" \u001b[31m[1, 2, 3]\u001b[0m: \"C:\\\\Users\\\\targo\\\\AppData\\\\Local\\\\Temp\\\\64de993b-4b59-41c5-815f-d4fad1b2f077\\\\hapi\\\\test\\\\hap
error:                       |                                                                                                                                                                                                                                                 
error:                       | Expected [Function] to throw an error with specified message                                                                                                                                                                                    
error:                       |                                                                                                                                                                                                                                                 
error:                       | at it (C:\Users\targo\AppData\Local\Temp\64de993b-4b59-41c5-815f-d4fad1b2f077\hapi\test\core.js:95:20                                                                                                                                           
error:                       |                                                                                                                                                                                                                                                 
error:                       | 114) Core _init() clears connections on close (HTTP):                                                                                                                                                                                           
error:                       |                                                                                                                                                                                                                                                 
error:                       | actual expected                                                                                                                                                                                                                                 
error:                       |                                                                                                                                                                                                                                                 
error:                       | 10                                                                                                                                                                                                                                              
error:                       |                                                                                                                                                                                                                                                 
error:                       | Expected 1 to equal specified value: 0                                                                                                                                                                                                          
error:                       |                                                                                                                                                                                                                                                 
error:                       | at it (C:\Users\targo\AppData\Local\Temp\64de993b-4b59-41c5-815f-d4fad1b2f077\hapi\test\core.js:586:50                                                                                                                                          
error:                       |                                                                                                                                                                                                                                                 
error:                       | 115) Core _init() clears connections on close (HTTPS):                                                                                                                                                                                          
error:                       |                                                                                                                                                                                                                                                 
error:                       | actual expected                                                                                                                                                                                                                                 
error:                       |                                                                                                                                                                                                                                                 
error:                       | 10                                                                                                                                                                                                                                              
error:                       |                                                                                                                                                                                                                                                 
error:                       | Expected 1 to equal specified value: 0                                                                                                                                                                                                          
error:                       |                                                                                                                                                                                                                                                 
error:                       | at it (C:\Users\targo\AppData\Local\Temp\64de993b-4b59-41c5-815f-d4fad1b2f077\hapi\test\core.js:625:50                                                                                                                                          
error:                       |                                                                                                                                                                                                                                                 
error:                       | 120) Core _stop() waits to stop until all connections are closed (HTTP):                                                                                                                                                                        
error:                       |                                                                                                                                                                                                                                                 
error:                       | actual expected                                                                                                                                                                                                                                 
error:                       |                                                                                                                                                                                                                                                 
error:                       | 12                                                                                                                                                                                                                                              
error:                       |                                                                                                                                                                                                                                                 
error:                       | Expected 1 to equal specified value: 2                                                                                                                                                                                                          
error:                       |                                                                                                                                                                                                                                                 
error:                       | at it (C:\Users\targo\AppData\Local\Temp\64de993b-4b59-41c5-815f-d4fad1b2f077\hapi\test\core.js:696:31                                                                                                                                          
error:                       |                                                                                                                                                                                                                                                 
error:                       | 122) Core _stop() immediately destroys unhandled connections:                                                                                                                                                                                   
error:                       |                                                                                                                                                                                                                                                 
error:                       | actual expected                                                                                                                                                                                                                                 
error:                       |                                                                                                                                                                                                                                                 
error:                       | 12                                                                                                                                                                                                                                              
error:                       |                                                                                                                                                                                                                                                 
error:                       | Expected 1 to equal specified value: 2                                                                                                                                                                                                          
error:                       |                                                                                                                                                                                                                                                 
error:                       | at it (C:\Users\targo\AppData\Local\Temp\64de993b-4b59-41c5-815f-d4fad1b2f077\hapi\test\core.js:749:31                                                                                                                                          
error:                       |                                                                                                                                                                                                                                                 
error:                       | 331) payload handles expect 100-continue:                                                                                                                                                                                                       
error:                       |                                                                                                                                                                                                                                                 
error:                       | Timed out (3000ms) - payload handles expect 100-continue                                                                                                                                                                                        
error:                       |                                                                                                                                                                                                                                                 
error:                       |                                                                                                                                                                                                                                                 
error:                       |                                                                                                                                                                                                                                                 
error:                       | 6 of 864 tests failed (4 skipped)                                                                                                                                                                                                               
error:                       | Test duration: 11090 ms                                                                                                                                                                                                                         
error:                       | Assertions count: 1736 (verbosity: 2.01)                                                                                                                                                                                                        
error:                       | No global variable leaks detected                                                                                                                                                                                                               
error:                       | Coverage: 99.93% (3/4040)                                                                                                                                                                                                                       
error:                       | lib/core.js missing coverage on line(s): 605                                                                                                                                                                                                    
error:                       | lib/route.js missing coverage on line(s): 394, 395                                                                                                                                                                                              
error:                       | Code coverage below threshold: 99.93 < 100                                                                                                                                                                                                      
error:                       | Linting results: No issues                                                                                                                                                                                                                      
error:                       |                                                                                                                                                                                                                                                 
error:                       |                                                                                                                                                                                                                                                 
error:                       | npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)                                                                                                                                           
error:                       | npm WARN inert@5.1.0 requires a peer of hapi@>=17.0.0 but none is installed. You must install peer dependencies yourself.                                                                                                                       
error:                       | npm WARN vision@5.3.3 requires a peer of hapi@17.x.x but none is installed. You must install peer dependencies yourself.                                                                                                                        
error:                       |                                                                                                                                                                                                                                                 
error:                       | npm ERR! Test failed.  See above for more details.                                                                                                                                                                                              
error:   done                | The smoke test has failed.
info:    duration            | test duration: 28312ms
```

</details>

**Comment by hueniverse** [comment]
Should be resolved now. Added Windows CI.

**Comment by MylesBorins** [comment]
getting failures when running locally

```
error:                       | Failed tests:
error:                       |
error:                       | 86) Core creates a server listening on a unix domain socket:
error:                       |
error:                       | listen EADDRINUSE /private/var/folders/pn/346shxv544x8r1t35lqdrnxr0000gn/T/b3136644-8fe2-458e-99f3-490a733e4de4/hapi/test/hapi-server.socket
error:                       |
error:                       | at Server.setupListenHandle [as _listen2] (net.js:1317:19)
error:                       | at listenInCluster (net.js:1382:12)
error:                       | at Server.listen (net.js:1480:5)
error:                       | at Promise (/private/var/folders/pn/346shxv544x8r1t35lqdrnxr0000gn/T/b3136644-8fe2-458e-99f3-490a733e4de4/hapi/lib/core.js:292:173)
error:                       | at new Promise (<anonymous>)
error:                       | at module.exports.internals.Core._listen (/private/var/folders/pn/346shxv544x8r1t35lqdrnxr0000gn/T/b3136644-8fe2-458e-99f3-490a733e4de4/hapi/lib/core.js:269
error:                       | at module.exports.internals.Core._start (/private/var/folders/pn/346shxv544x8r1t35lqdrnxr0000gn/T/b3136644-8fe2-458e-99f3-490a733e4de4/hapi/lib/core.js:243:
error:                       |
error:                       |
error:                       | 1 of 870 tests failed
```

**Comment by cjihrig** [comment]
@MylesBorins can you give it another try - a fix has been landed which should address it.

**Comment by MylesBorins** [comment]
@cjihrig has that fix been pushed in a release? Still seeing errors running locally

**Comment by cjihrig** [comment]
It hasn't been included in a release yet. I assumed you were cloning the repo to run the tests since the [tests aren't published to npm](https://github.com/hapijs/hapi/blob/master/.npmignore).

**Comment by MylesBorins** [comment]
@cjihrig CITGM gets the latest version from npm and then grabs the tarball from github (which afaict has the tests in it). This fix will need to be published before we can land this

**Comment by cjihrig** [comment]
A new release of hapi (17.5.4) went out 13 days ago.

**Comment by MylesBorins** [comment]
Running locally and still having failures

```
error:   failure             | The canary is dead:
error:   failing module(s)   |
error:   module name:        | hapi
error:   version:            | 17.5.4
error:   error:              | The canary is dead:
error:   error:              | undefinedadded 240 packages from 272 contributors and audited 387 packages in 3.601s
error:                       | found 0 vulnerabilities
error:                       |
error:                       |
error:                       | > hapi@17.5.4 test /private/var/folders/p9/jw8_3dz56mz6yxdfd778p6lr00dkv3/T/e81a6f73-df96-4099-bbd1-b025b06ab5ea/hapi
error:                       | > lab -a code -t 100 -L -m 3000
error:                       |
error:                       |
error:                       |
error:                       | ..................................................
error:                       | ...................................x..............
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | ..................................................
error:                       | .....................
error:                       |
error:                       | Failed tests:
error:                       |
error:                       | 86) Core creates a server listening on a unix domain socket:
error:                       |
error:                       | listen EADDRINUSE /private/var/folders/p9/jw8_3dz56mz6yxdfd778p6lr00dkv3/T/e81a6f73-df96-4099-bbd1-b025b06ab5ea/hapi/test/hapi-server.socket
error:                       |
error:                       | at Server.setupListenHandle [as _listen2] (net.js:1343:19)
error:                       | at listenInCluster (net.js:1401:12)
error:                       | at Server.listen (net.js:1496:5)
error:                       | at Promise (/private/var/folders/p9/jw8_3dz56mz6yxdfd778p6lr00dkv3/T/e81a6f73-df96-4099-bbd1-b025b06ab5ea/hapi/lib/core.js:292:173)
error:                       | at new Promise (<anonymous>)
error:                       | at module.exports.internals.Core._listen (/private/var/folders/p9/jw8_3dz56mz6yxdfd778p6lr00dkv3/T/e81a6f73-df96-4099-bbd1-b025b06ab5ea/hapi/lib/core.js:269:175)
error:                       | at module.exports.internals.Core._start (/private/var/folders/p9/jw8_3dz56mz6yxdfd778p6lr00dkv3/T/e81a6f73-df96-4099-bbd1-b025b06ab5ea/hapi/lib/core.js:243:166)
error:                       | at <anonymous>
error:                       |
error:                       |
error:                       | 1 of 871 tests failed
error:                       | Test duration: 7997 ms
error:                       | Assertions count: 1765 (verbosity: 2.03)
error:                       | No global variable leaks detected
error:                       | Coverage: 100.00%
error:                       | Linting results: No issues
error:                       |
error:                       |
error:                       | npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
error:                       | npm WARN inert@5.1.0 requires a peer of hapi@>=17.0.0 but none is installed. You must install peer dependencies yourself.
error:                       | npm WARN vision@5.4.0 requires a peer of hapi@17.x.x but none is installed. You must install peer dependencies yourself.
error:                       |
error:                       | npm ERR! Test failed.  See above for more details.
error:   done                | The smoke test has failed.
info:    duration            | test duration: 17339ms
```

**Comment by gdams** [comment]
so Hapi seems to be passing on Linux but not macOS now using CITGM (https://modules.cloudnativejs.io/module/hapi/module_version/17.5.4)

**Comment by richardlau** [comment]
> listen EADDRINUSE /private/var/folders/p9/jw8_3dz56mz6yxdfd778p6lr00dkv3/T/e81a6f73-df96-4099-bbd1-b025b06ab5ea/hapi/test/hapi-server.socket

This path is 122 characters long which is too long for a Unix domain socket. The first 94 characters look like what CITGM has determined the temp directory is to test modules in. Is the default temp directory on macOS usually like that?

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/85/console

**Comment by devinivy** [comment]
Hello, member of the hapi TSC here.  There was a recent node regression in v15.5.0 that would have been caught if hapi were in citgm, which was a great reminder that this PR is still up in the air.  Could we revive this and try to land it?  Feel free to reach out to me for any context/issues on the hapi side.

**Comment by targos** [comment]
This PR adds the `hapi` module, which is deprecated on npm. Should we use `@hapi/hapi` instead?
Also I guess we should change the list of active maintainers to ping in case of an issue? currently this PR adds `"maintainers": ["hueniverse", "DavidTPate", "AdriVanHoudt"]`

**Comment by devinivy** [comment]
Yes, we should use the @hapi/hapi module.  I anticipate @hueniverse will not be interested in getting notified anymore, and maybe he will confirm that for us.  @AdriVanHoudt and @DavidTPate were volunteers from https://github.com/nodejs/citgm/issues/8, and if they still want to help with hapi support in citgm then that is great and appreciated (but I know that was also a long time ago!).  We should at least get one hapi TSC member in this list, and I would be happy to be that person.

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/131/

**Comment by targos** [comment]
It looks like we need to skip it on Node.js v10 because of the use of private class fields:

```
 > @hapi/hapi@20.0.3 test /home/iojs/tmp/citgm_tmp/36a5430f-0049-4ed7-9b40-cf6eb562a3a3/@hapi/hapi
 > lab -a @hapi/code -t 100 -L -m 5000
 Error requiring file: /home/iojs/tmp/citgm_tmp/36a5430f-0049-4ed7-9b40-cf6eb562a3a3/@hapi/hapi/test/auth.js
 Invalid or unexpected token
 /home/iojs/tmp/citgm_tmp/36a5430f-0049-4ed7-9b40-cf6eb562a3a3/@hapi/hapi/node_modules/@hapi/teamwork/lib/index.js:8
     #meetings = null;
     ^
 SyntaxError: Invalid or unexpected token
```

**Comment by targos** [comment]
Also on macOS and AIX where two tests fail:

```
 Failed tests:
   391) Request active() exits handler early when request is no longer active:
       Timed out (5000ms) - Request active() exits handler early when request is no longer active
   415) Request _postCycle() skips onPreResponse when validation terminates request:
       Timed out (5000ms) - Request _postCycle() skips onPreResponse when validation terminates request
 2 of 967 tests failed
```

**Comment by devinivy** [comment]
Awesome, thanks.  We can look into the failing tests 👍 I can confirm that hapi supports node v12+.

**Comment by targos** [comment]
New CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/132/

**Comment by targos** [comment]
There's still the issue of tests depending on the presence of `lsof`:

```
   175) Core ext() onPreResponse cleans unused file stream when response is overridden:
       spawn lsof ENOENT
       at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
       at onErrorNT (internal/child_process.js:465:16)
       at processTicksAndRejections (internal/process/task_queues.js:80:21)
   805) transmission marshal() closes file handlers when not reading file stream:
       spawn lsof ENOENT
       at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
       at onErrorNT (internal/child_process.js:465:16)
       at processTicksAndRejections (internal/process/task_queues.js:80:21)
   806) transmission marshal() closes file handlers when not using a manually open file stream:
       spawn lsof ENOENT
       at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
       at onErrorNT (internal/child_process.js:465:16)
       at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by AdriVanHoudt** [comment]
I'm happy to make sure hapi gets into citgm and making sure that future failures get resolved/reported to hapi.

As for the latest errors.
There has been fixes specifically for this https://github.com/hapijs/hapi/pull/3744 in the past.
I'm not familiar with ChildProcess.spawn or how that error looks, it might be that the ignore is not correct?

@devinivy it might be good to decide on how to relay breakage, do I just ping (Slack or here) or open up an issue on the hapi repo?

**Comment by AdriVanHoudt** [comment]
> Also on macOS and AIX where two tests fail:
> 
> ```
>  Failed tests:
>    391) Request active() exits handler early when request is no longer active:
>        Timed out (5000ms) - Request active() exits handler early when request is no longer active
>    415) Request _postCycle() skips onPreResponse when validation terminates request:
>        Timed out (5000ms) - Request _postCycle() skips onPreResponse when validation terminates request
>  2 of 967 tests failed
> ```

I can confirm these failures on my MacOS 11.1 node 14.15.4.
MacOS 10.15.7 did pass on Github Actions CI with node 14.15.1 https://github.com/hapijs/hapi/runs/1622790060?check_suite_focus=true
What I get from Jenkins (not familiar with it and not super straightforward to navigate) these failures also happen on MacOS 10.15.4 node 14 https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=osx1015/994/injectedEnvVars/

**Comment by kanongil** [comment]
The `lsof` tests are not critical to the suite, and are already conditionally omitted on windows. We could revise the condition to check for `lsof` availability instead.

**Comment by devinivy** [comment]
For those following along, there are some proposed fixes for the osx, aix, and lsof-related failures here: https://github.com/hapijs/hapi/pull/4221 🤞

**Comment by devinivy** [comment]
@targos those fixes landed in hapi, so we should be ready for another run.  I wasn't able to reproduce the issues on all platforms because I do not have access to them, but I made an effort to reduce or eliminate timing dependence in these failing tests, and I cleaned-up the lsof-related problems.  If after the run any issues remain on OSX or AIX, is there any way we could utilize the citgm CI to help debug them?

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/136/console

**Comment by targos** [comment]
Is it still supposed to fail on Node.js 15 ?

**Comment by devinivy** [comment]
In node 15.5.0 there was a change that broke hapi https://github.com/hapijs/hapi/issues/4208 https://github.com/nodejs/node/pull/33035.  This change to node was reverted in 15.6.0, and hapi's test suite was fixed.  Now on 15.7.0 it seems there's a new issue.  I can reproduce it locally so I will check it out from the hapi perspective, but it does seem like it relates to some change in 15.7.0 (possibly https://github.com/nodejs/node/pull/36821?).

**Comment by kanongil** [comment]
Seems very likely.

Hapi relies on the `'aborted'` event triggering before 'end' / 'close' / 'error' to signal it: https://github.com/hapijs/hapi/blob/6a3452477de7a512fb0022f3a06d45d527b82e48/lib/request.js#L716-L722.

And the failing test relies on the signal.

**Comment by targos** [comment]
@nodejs/http ^

**Comment by ronag** [comment]
> Hapi relies on the 'aborted' event triggering before 'end' / 'close' / 'error' to signal it: hapijs/hapi@6a34524/lib/request.js#L716-L722.

That link looks at `abort` not `aborted`?

**Comment by kanongil** [comment]
Yeah, confusingly it registers on 'aborted', and forwards it as 'abort'.

**Comment by dnlup** [comment]
Just thinking out loud here.

The order in which the `aborted` event is emitted should not have changed by https://github.com/nodejs/node/pull/36821.

[`AbortIncoming`](https://github.com/nxtedition/node/blob/43fc062f278c22f4284b55dbf842525bf464d5de/lib/_http_server.js#L588) calls `request.destroy` which in turn emits `aborted`  and then `close`/`error` (https://github.com/nxtedition/node/blob/43fc062f278c22f4284b55dbf842525bf464d5de/lib/_http_incoming.js#L172).

I'll try to verify on the failing test, though.

**Comment by ronag** [comment]
@dnlup: I think this has to do with server side, not client side.

**Comment by ronag** [comment]
I'd suggest we try a revert of https://github.com/nodejs/node/commit/708728ddccfabacace6ae40b7b7b9cd2726a8a14

**Comment by devinivy** [comment]
Just checking in: is there anything we can do on the hapi side to help move this forward, or is this being looked into on the node side to determine whether the cause was https://github.com/nodejs/node/commit/708728ddccfabacace6ae40b7b7b9cd2726a8a14?

**Comment by dnlup** [comment]
Apologies for the late reply. The failing test seems to be in `test/transmission.js`, and reverting https://github.com/nodejs/node/commit/708728ddccfabacace6ae40b7b7b9cd2726a8a14 from the `v15.7.0` tag makes the test pass again, so your suspicion was right.

**Comment by dnlup** [comment]
Diggin a little bit further, before the change what happened was:

1. `socketOnEnd` is called
2. `abortIncoming` is called on `req`
3. `socketOnClose` is called
4. `abortIncoming` is called again

While with the changes:

1. `socketOnEnd` is called
3. `socketOnClose` is called
4. `abortIncoming` is called on `req`

This makes sense to me on the Node side. I have to dig on the hapi side. You would be faster than me @devinivy on that part, assuming these pieces of information are useful in any way.

**Comment by devinivy** [comment]
@dnlup hey, no sweat.  Will take a look on the hapi side, thanks!

**Comment by devinivy** [comment]
@dnlup node v15.7.0 did uncover a bug on our end!  The issue for us wasn't the double emit of abort, but the timing between abort and close (they now seems to happen in the same tick, more info in https://github.com/hapijs/hapi/pull/4234.) We were able to ship a fix in hapi v20.1.1.  We are ready for another CI run 🤞 👍

**Comment by targos** [comment]
GitHub CI: https://github.com/nodejs/citgm/actions/runs/656723779

**Comment by targos** [comment]
Jenkins CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/144/console

**Comment by dnlup** [comment]
@devinivy Great news you were able to find the problem and fix it. Thank you!

**Pull request merged**
