### PR TITLE
lookup: unskip jquery on Windows

### PR DESCRIPTION
**Pull request by bzoz**
`jquery` tests pass on Windows

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by targos** [comment]
https://ci.nodejs.org/blue/organizations/jenkins/citgm-smoker-pipeline/detail/citgm-smoker-pipeline/30/pipeline

**Comment by targos** [comment]
CI is unhappy. This seems to be the problem:

```
08:55:14 error:                     | Done.                                                                                                                                                                                   
08:55:14 error:                     | Running "karma:main" (karma) task                                                                                                                                                       
08:55:14 error:                     | 12 07 2018 12:54:32.856:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/                                                                                               
08:55:14 error:                     | 12 07 2018 12:54:32.859:INFO [launcher]: Launching browser ChromeHeadless with concurrency 3                                                                                            
08:55:14 error:                     | 12 07 2018 12:54:32.867:INFO [launcher]: Starting browser ChromeHeadless                                                                                                                
08:55:14 error:                     | 12 07 2018 12:54:52.867:WARN [launcher]: ChromeHeadless have not captured in 20000 ms, killing.                                                                                         
08:55:14 error:                     | 12 07 2018 12:54:54.868:WARN [launcher]: ChromeHeadless was not killed in 2000 ms, sending SIGKILL.                                                                                     
08:55:14 error:                     | 12 07 2018 12:54:56.869:WARN [launcher]: ChromeHeadless was not killed by SIGKILL in 2000 ms, continuing.                                                                               
08:55:14 error:                     | Warning: Task "karma:main" failed. Use --force to continue.  
```

**Comment by bzoz** [comment]
I've tried [running the CI](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/35/) and it passes. Is there a special way to start a CI run?

**Comment by targos** [comment]
I think it passes because nothing actually ran. There is no "win10" machine in CI. Possible values are: `win2008r2-vs2017` `win10-vs2015` `win2016-vs2017`

**Comment by bzoz** [comment]
Yes, that could be a reason for all the tests to pass 😃 

Another try: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/36/

**Comment by BridgeAR** [comment]
New CI https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/39/

**Comment by BridgeAR** [comment]
This failed on all windows platforms. I guess this should be closed. If I am wrong, please reopen.

**Pull request closed without merging**
