### PR TITLE
lookup: unskip bluebird, bson and radium

### PR DESCRIPTION
**Pull request by targos**
They pass on my machine.

Do we have a way test 3 modules in one CI run? @richardlau

### CODE REVIEW

**Comment by richardlau** [comment]
> Do we have a way test 3 modules in one CI run? @richardlau

Untested, but maybe `--includeTags` to `citgm-all`? The module names are available as tags: https://github.com/nodejs/citgm/blob/62ade10c03fa7006a9518b8235b06d4532bfcbb6/lib/check-tags.js#L17

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/72/

**Comment by targos** [comment]
New CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/73/

**Comment by targos** [comment]
It's green :)

**Comment by richardlau** [comment]
> 
> 
> It's green :)

Only because everything was skipped? Looks like https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/73/ was run against `citgm` (i.e. with the skips) rather than `targos/citgm#unskip`.

**Comment by targos** [comment]
🤦‍♂ 

Better: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/74/console

Only Windows fails because npm puts a shell script at `node_modules/.bin/_mocha` instead of a symlink.
Should we skip the platform?

**Comment by BridgeAR** [comment]
@targos that's probably best. I wonder if it makes sense to add a comment field to our JSON entries to explain why we skip things. That way it becomes easier to unzip them as soon as a problem is resolved.

**Comment by targos** [comment]
Adding a general comment field to the lookup sound like a good idea

**Comment by targos** [comment]
New CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/75/console

**Pull request merged**
