### PR TITLE
chore: Replace EOL Node 14/19 with Node 20

### PR DESCRIPTION
**Pull request by nschonni**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/HEAD/CONTRIBUTING.md)

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Review by richardlau — APPROVED** [review]

**Comment by nschonni** [comment]
Looks like it might still be picking up some old ones from https://github.com/pkgjs/action/blob/main/.github/workflows/node-test.yaml but I'm not sure if that's from the pinned `pkgjs/action/.github/workflows/node-test.yaml@v0.1`, or something else. Not a blocker for this, but probably needs another PR too

**Comment by richardlau** [comment]
> Looks like it might still be picking up some old ones from https://github.com/pkgjs/action/blob/main/.github/workflows/node-test.yaml but I'm not sure if that's from the pinned `pkgjs/action/.github/workflows/node-test.yaml@v0.1`, or something else. Not a blocker for this, but probably needs another PR too

I think that's because 14 is in our `engines`: https://github.com/nodejs/citgm/blob/dd3b422f529376ec9805492cd3fe556bf4bee070/package.json#L92-L94

**Comment by nschonni** [comment]
@richardlau you're right, that seems to have fixed it

**Review by richardlau — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
