### PR TITLE
refactor output logging to use winston, add verbose levels

### PR DESCRIPTION
**Pull request by jasnell**
Bump version to v0.2.2

Using winston for logging output now.

`--verbose` can now take one of three options:

  `info`, `error`, `warn`

The default is `info`, which is the most verbose level.

/cc @rvagg

### CODE REVIEW

**Comment by rvagg** [comment]
good I think, hard to review with so much s/var/const diff noise but SGTM

**Comment by jasnell** [comment]
Yeah, just cleaning a few things up in the process.. will be landing shortly

**Comment by thefourtheye** [comment]
Hmmmm, using `const` everywhere... Older Nodes will not be supported?

**Comment by rvagg** [comment]
`const` is available on 0.10, that's all we need care about

**Comment by jasnell** [comment]
'use strict' with const not so much tho, so we need to watch that. Which
raises the question: do we need the smoke test utility for older versions
of Node or are we focusing on new releases only?

**Comment by rvagg** [comment]
I'm pretty relaxed about 0.10 and 0.12, I don't see major changes going in there, however if we get this right and it starts working well it may be very tempting to apply the exact same procedure to those branches

**Comment by jasnell** [comment]
Landed in 9c8b6ad. May need to revisit the `const` change separately.

**Pull request closed without merging**
