### PR TITLE
Adds integration tests for Yarn

### PR DESCRIPTION
**Pull request by arcanis**
We merged #905 without running the full suite of integration tests to make sure that we were testing at least *something*. This PR aims to enable a couple of the most important integration tests (still not all of them).

##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [x] documentation is changed or added
- [x] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/HEAD/CONTRIBUTING.md)

### CODE REVIEW

**Comment by targos** [comment]
https://github.com/nodejs/citgm/actions/runs/6652341543

**Comment by arcanis** [comment]
The test failures seem unrelated with my change (I see they occur in main already: https://github.com/nodejs/citgm/actions/runs/6604240669/job/17938186004#step:14:770).

**Comment by targos** [comment]
You can disregard the test failure but https://github.com/nodejs/citgm/actions/runs/6652341543 shows multiple failures that may be related.

**Comment by arcanis** [comment]
Can you retry them? I think I fixed them in https://github.com/yarnpkg/berry/pull/5875

**Comment by targos** [comment]
New run: https://github.com/nodejs/citgm/actions/runs/6652341543

**Comment by arcanis** [comment]
All green!

**Comment by targos** [comment]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/228/console

**Comment by arcanis** [comment]
The three failures seem infra problems:

[ubuntu1804-64](https://ci.nodejs.org/job/citgm-smoker-nobuild/1533/nodes=ubuntu1804-64/console):
```
08:40:24 node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
08:40:24 Build step 'Execute shell' marked build as failure
```

[rhel8-ppc64le](https://ci.nodejs.org/job/citgm-smoker-nobuild/1533/nodes=rhel8-ppc64le/console) & [fedora-last-latest-x64](https://ci.nodejs.org/job/citgm-smoker-nobuild/1533/nodes=fedora-last-latest-x64/console):
```
08:33:42 curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
08:33:42 Build step 'Execute shell' marked build as failure
```

**Comment by targos** [comment]
Agreed.

**Review by targos — APPROVED** [review]

**Pull request merged**
