### PR TITLE
add --loglevel, npm-loglevel, and npm-config-nodedir

### PR DESCRIPTION
**Pull request by jasnell**
pass `npm-loglevel` and `npm-config-nodedir` env vars to npm install.
add `--loglevel` command line switch

/cc @rvagg

### CODE REVIEW

**Comment by rvagg** [comment]
I'm fine with this, as long as nobody has any objections to completely hiding anything but warnings with no way to opt-out

**Comment by jasnell** [comment]
Should I add a loglevel switch to citgm itself?

**Comment by rvagg** [comment]
well, you said you weren't happy with the complexity of the cmdline switches atm so perhaps defer that until someone asks for it, npm is just a means to an end here

**Comment by jasnell** [comment]
Works for me.

**Comment by jasnell** [comment]
Landed in 445e0c0

**Pull request closed without merging**
