### PR TITLE
lookup: add wrtc

### PR DESCRIPTION
**Pull request by markandrus**
May I add [wrtc](https://www.npmjs.com/package/wrtc) to citgm?

**Hard Requirements**

- [x] Module source code must be on Github.
- [x] Published versions must include a tag on Github
- [x] The test process must be executable with only the commands `npm install && npm test` or (`yarn install && yarn test`) using the tarball downloaded from the Github tag mentioned above
- [x] The tests pass on supported major release lines
- [x] The maintainers of the module remain responsive when there are problems
- [x] At least one module maintainer must be added to the lookup maintainers field

**Soft Requirements**

At least one of:

- [x] The module must be actively used by the community OR
- [ ] The module must be heavily depended on OR
- [x] The module must cover unique portions of our API OR
- [ ] The module fits into a key category (e.g. Testing, Streams, Monitoring, etc.) OR
- [ ] The module is under the Node.js foundation Github org OR
- [ ] The module is identified as an important module by a Node.js Working Group

### CODE REVIEW

**Comment by BridgeAR** [comment]
LGTM in case the tests pass on all platforms.

**Comment by targos** [comment]
CI (pending): https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/76/console

**Comment by markandrus** [comment]
Thanks for taking a look. I see some failures on some of the platforms. I'll try to assess them in the coming days and update this PR.

**Comment by markandrus** [comment]
STUN failures on the following platforms (I was wondering if ports were blocked, but these sometimes pass&hellip;):

- debian8-64
- debian9-64
- fedora-last-latest-x64
- fedora-latest-x64
- ubuntu-1404-64
- ubuntu-1604-64
- ubuntu-1804-64
- win2008r2-vs2017

GLIBC_2.16 not found (ought to just exclude):

- ubuntu-1204-64

`C:\Users\ADMINI~1\AppData\Local\Temp\1\jenkins1937379431077144091.sh: line 18: pgrep: command not found` (one-off issue?):

- win2008r2-vs2017

**Comment by markandrus** [comment]
I've pushed a new wrtc release. It skips the tests that appeared to fail. I've also marked "ubuntu-1204-64" to be skipped in `lib/lookup.json`. I hope this gets the tests passing in CI.

**Comment by BridgeAR** [comment]
CI https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/82/ (pending)

**Comment by markandrus** [comment]
Unfortunately I must retract this. I don't have time to support it.

**Pull request closed without merging**
