### PR TITLE
lookup: updated skip/flaky tags for AIX

### PR DESCRIPTION
**Pull request by gdams**
Updated flaky/skip tags for AIX

### CODE REVIEW

**Comment by MylesBorins** [comment]
LGTM

**Comment by gibfahn** [comment]
This is currently blocked by https://github.com/nodejs/citgm/pull/325 (as at the moment CitGM is completely filling up the ~1GB `/tmp` directory on the CI AIX machines).

**Comment by MylesBorins** [comment]
this can still land before the tmp fix

**Comment by gibfahn** [comment]
@MylesBorins 
>this can still land before the tmp fix

well I guess it *could*, but we can't really test it, and I don't think we should mark things as flaky without a CI run to confirm.

@gdams 

Could you include the failures for these modules? It'll be helpful for fixing them later.

**Comment by MylesBorins** [comment]
thanks for the clarification, I thought they were confirmed

**Pull request merged**
