### PR TITLE
deps: update yargs to 7.0.1

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gibfahn** [comment]
`semver-major`?

**Comment by gdams** [comment]
doesn't look like there are any breaking changes: https://github.com/yargs/yargs/releases/tag/v6.4.0

**Comment by gdams** [comment]
the changelog doesn't indicate any semver major features, I should perhaps run a CI on 0.10 and 0.12 to confirm

**Comment by gibfahn** [comment]
Looks like some `const` in there, isn't that `semver-major`?

https://github.com/yargs/yargs/compare/v6.6.0...v7.0.1#diff-65b0a1afe6429797016251d9f7a20e7f

**Comment by gdams** [comment]
Yep good spot

**Pull request merged**
