### PR TITLE
Added pino

### PR DESCRIPTION
**Pull request by mcollina**
Adds the pino logger. It currently has 2 mln downloads/month, and it's probably worthwhile to check it before release of Node.

Note that it currently does not pass on Windows with v14, likely due to https://github.com/nodejs/node/issues/33166 or some other regression. See https://github.com/pinojs/pino/pull/839 for some details.

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/113/

**Comment by targos** [comment]
Note that it passed on all platforms and Node.js versions, including v14/windows 10: https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=win10-vs2019/829/

**Comment by mcollina** [comment]
very interesting :/. I can get a consistent fail on Github Actions. Anyway, better in this way.

**Pull request merged**
