### PR TITLE
lookup: skip yargs on >=12

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by BridgeAR** [comment]
@bcoe we do not need this in case you publish a new version. It's already fixed on master.

**Comment by targos** [comment]
I confirm it works with version 13.2.3. That version is on GitHub but not published to npm yet.

**Comment by bcoe** [comment]
@targos @BridgeAR:

```bash
$ npm dist-tag ls yargs
latest: 13.2.4
``

sorry for dropping the ball on that.

**Comment by targos** [comment]
Thanks, this is resolved!

**Pull request closed without merging**
