### PR TITLE
lookup: re-add undici

### PR DESCRIPTION
**Pull request by Trott**
##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/HEAD/CONTRIBUTING.md)

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by mcollina** [comment]
CITGM: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3273/

**Comment by mcollina** [comment]
Fresh CITGM: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3303/

**Comment by mcollina** [comment]
Fresh CITGM: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3334/

**Comment by targos** [comment]
Failure from https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3334/nodes=rhel8-x64/

```
 # Subtest: test/connect-timeout.js
     # Subtest: priotorise socket errors over timeouts
         1..1
         not ok 1 - should be equal
           ---
           compare: ===
           at:
             line: 16
             column: 9
             file: test/connect-timeout.js
           stack: |
             test/connect-timeout.js:16:9
           source: |2
                 .catch((err) => {
                   t.equal(err.code, 'ENOTFOUND')
             --------^
                 })
           diff: |
             --- expected
             +++ actual
             @@ -1,1 +1,1 @@
             -ENOTFOUND
             +UND_ERR_CONNECT_TIMEOUT
           ...
         
         # failed 1 test
     not ok 1 - priotorise socket errors over timeouts # time=1074.305ms
     
     # Subtest: connect-timeout
         1..1
         ok 1 - type is ConnectTimeoutError
     ok 2 - connect-timeout # time=1003.865ms
     
     # Subtest: connect-timeout
         1..1
         ok 1 - type is ConnectTimeoutError
     ok 3 - connect-timeout # time=1003.412ms
     
     1..3
     # failed 1 of 3 tests
     # time=5100.208ms
 not ok 30 - test/connect-timeout.js # time=5100.208ms
   ---
   env: {}
   file: test/connect-timeout.js
   timeout: 60000
   command: /home/iojs/build/workspace/citgm-smoker/smoker/bin/node
   args:
     - --expose-gc
     - test/connect-timeout.js
   stdio:
     - 0
     - pipe
     - 2
   cwd: /home/iojs/tmp/citgm_tmp/1031071a-c640-4205-a5f9-5946076938c2/undici
   exitCode: 1
   ...
```

**Comment by mcollina** [comment]
@nodejs/undici I need some help in making the tests less flaky so we can re-land this.

**Comment by ronag** [comment]
I think you fixed connect-timeout? What tests are still flaky?

**Comment by mcollina** [comment]
Let's try again with v5.26.5.

Fresh CITGM: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3337/

**Comment by RafaelGSS** [comment]
Full CITGM for undici https://ci.nodejs.org/job/citgm-smoker/3383/

(I'm not sure if I'm configuring it correctly)

**Comment by targos** [comment]
@RafaelGSS You used the wrong job. It should be https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/

**Comment by panva** [comment]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/237/

(v18 and v20)

**Comment by mcollina** [comment]
IMHO this should never have been removed in the first place (I said as much multiple times). Let's land this even if it fails and refine.

**Pull request merged**
