### PR TITLE
lookup: add shot

### LINKED ISSUE #457: Add Shot to the mix
Shot has been broken twice by Node 8, I think it is doing some stuff very close to the internals, and it might be good to have them on board.

https://github.com/hapijs/shot

On node 8.2.0 shots tests aborts: https://github.com/nodejs/node/issues/14386

cc @hueniverse

### PR DESCRIPTION
**Pull request by Marsup**
##### Checklist

- [X] `npm test` passes

#### Hard Requirements

- [X] Module source code must be on Github.
- [X] Published versions must include a tag on Github
- [X] The test process must be executable with only the commands `npm install && npm test` using the tarball downloaded from the Github tag mentioned above
- [x] The tests pass on supported major release lines
- [X] The maintainers of the module remain responsive when there are problems
- [X] At least one module maintainer must be added to the lookup maintainers field

#### Soft Requirements

At least one of:

- [X] The module must be actively used by the community OR
- [ ] The module must be heavily depended on OR
- [x] The module must cover unique portions of our API OR
- [ ] The module fits into a key category (e.g. Testing, Streams, Monitoring, etc.) OR
- [ ] The module is under the Node.js foundation Github org OR
- [ ] The module is identified as an important module by a Node.js Working Group

Fixes #457, it's failing on node 8.2.0 so I can't tick that box.

### CODE REVIEW

**Comment by gibfahn** [comment]
Smoke test on Node 4, 6, and 8: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/1/console

**Comment by gibfahn** [comment]
cc/ @mtharrison to make sure you're okay with this (and with us pinging you if we have issues with this module).

Is there anyone else we should be adding to the `maintainers` list?

**Comment by targos** [comment]
Should we merge?

**Comment by gibfahn** [comment]
CI again (just to be sure): https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/3/console

**Comment by mtharrison** [comment]
@gibfahn yes I'm ok with it and you can ping me for sure.

**Comment by MylesBorins** [comment]
landed in 718fd75dee

**Pull request closed without merging**
