### PR TITLE
logger: add --loglevel as an alias to --verbose

### PR DESCRIPTION
**Pull request by gdams**
Closes: #371

##### Checklist

- [x] `npm test` passes
- [x] documentation is changed or added
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by gdams** [comment]
cc @richardlau

**Comment by gdams** [comment]
@MylesBorins are you happy for me to land this?

**Comment by MylesBorins** [comment]
@gdams are you 100% it works as --loglevel and not -loglevel?

If so it LGTM

**Comment by gdams** [comment]
yeah this definitely only works with `--loglevel` and fails with `-loglevel`

**Pull request merged**
