### PR TITLE
lookup: mark yeoman-generator as flaky

### PR DESCRIPTION
**Pull request by al-k21**
##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gdams** [comment]
I'm a little hesitant to make yeoman-generator as flaky on an entire release version, do we know why this is failing? And is it definitely flaky or should we be skipping ?

**Comment by gibfahn** [comment]
The test fails reliably, and started failing in `8.0.0`. @SBoudrias, @sindresorhus do you have any more info on why this module has test failures on Node 8.x?

<details><summary>Failures:</summary>

```js
  8 failing

  1) Base #option() disallows Boolean options starting with no-:
     AssertionError [ERR_ASSERTION]: Missing expected exception.
      at innerThrows (assert.js:609:7)
      at Function.throws (assert.js:625:3)
      at Context.<anonymous> (test/base.js:682:14)

  2) Base #option() disallows Boolean options starting with no-:
     AssertionError [ERR_ASSERTION]: Missing expected exception.
      at innerThrows (assert.js:609:7)
      at Function.throws (assert.js:625:3)
      at Context.<anonymous> (test/base.js:682:14)

  3) Base #composeWith() runs the composed generators:
     Uncaught Error: You don’t seem to have a generator with the name “composed:gen” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-composed:gen.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators. 

If yo cannot find the generator, run yo doctor to troubleshoot your system.
      at Environment.create (node_modules/yeoman-environment/lib/environment.js:300:7)
      at Dummy.composeWith (lib/index.js:9:19585)
      at Context.<anonymous> (test/base.js:749:18)

  4) Base #composeWith() runs the composed generators:
     Uncaught Error: You don’t seem to have a generator with the name “composed:gen” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-composed:gen.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators. 

If yo cannot find the generator, run yo doctor to troubleshoot your system.
      at Environment.create (node_modules/yeoman-environment/lib/environment.js:300:7)
      at Dummy.composeWith (lib/index.js:9:19585)
      at Context.<anonymous> (test/base.js:749:18)

  5) Base #composeWith() when passing a local path to a generator runs the composed generator:
     AssertionError [ERR_ASSERTION]: missing path
      at require (internal/module.js:11:18)
      at Dummy.composeWith (lib/index.js:9:19080)
      at Context.<anonymous> (test/base.js:798:20)

  6) Base #composeWith() when passing a local path to a generator pass options and arguments to the composed generators:
     AssertionError [ERR_ASSERTION]: missing path
      at require (internal/module.js:11:18)
      at Dummy.composeWith (lib/index.js:9:19080)
      at Context.<anonymous> (test/base.js:806:20)

  7) Base #composeWith() when passing a local path to a generator pass options and arguments to the composed generators:
     AssertionError [ERR_ASSERTION]: missing path
      at require (internal/module.js:11:18)
      at Dummy.composeWith (lib/index.js:9:19080)
      at Context.<anonymous> (test/base.js:806:20)

  8) Base #composeWith() when passing a local path to a generator sets correct metadata on the Generator constructor:
     AssertionError [ERR_ASSERTION]: missing path
      at require (internal/module.js:11:18)
      at Dummy.composeWith (lib/index.js:9:19080)
      at Context.<anonymous> (test/base.js:815:20)
```

</details>

**Comment by BridgeAR** [comment]
This is now obsolete and should be closed.

**Comment by MylesBorins** [comment]
Thanks for chiming in @BridgeAR

**Pull request closed without merging**
