### PR TITLE
lookup: unskip zeromq on Windows

### PR DESCRIPTION
**Pull request by bzoz**
Unmarks the zeromq package as skiped on win32

##### Checklist

- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by targos** [comment]
CI: https://ci.nodejs.org/blue/organizations/jenkins/citgm-smoker-pipeline/detail/citgm-smoker-pipeline/24/pipeline

**Comment by BridgeAR** [comment]
New CI https://ci.nodejs.org/blue/organizations/jenkins/citgm-smoker-pipeline/detail/citgm-smoker-pipeline/41/pipeline

**Comment by targos** [comment]
All runs failed on Windows

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/83/

**Comment by targos** [comment]
I'm marking this WIP because it fails on all windows hosts in CI

**Comment by targos** [comment]
Launched https://github.com/targos/citgm/actions/runs/627108721 to check the status

**Comment by targos** [comment]
I opened https://github.com/nodejs/citgm/pull/850 as an alternative because zeromq does not support `npm test` anymore.

**Pull request closed without merging**
