### PR TITLE
[WIP] add nan to lookup.json

### PR DESCRIPTION
**Pull request by mcollina**
I've added nan to lookup.json. I think it should be there, and we should do our best to keep this up to date and supported.

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mcollina** [comment]
This seems a major problem and a failure on our side.
I fear NAN might be using some of the deprecated V8 APIs.

**Comment by richardlau** [comment]
> 
> 
> It agree it should be there, but right now `citgm nan` fails on all supported release lines.

The test bindings need to be built: https://github.com/nodejs/nan#tests

> ### Tests
> 
> To run the NAN tests do:
> 
> ``` sh
> npm install
> npm run-script rebuild-tests
> npm test
> ```
> 
> Or just:
> 
> ``` sh
> npm install
> make test
> ```

I don't think we currently have a way in `lookup.json` of  accommodating this.

**Comment by richardlau** [comment]
> 
> 
> > It agree it should be there, but right now `citgm nan` fails on all supported release lines.
> 
> The test bindings need to be built: https://github.com/nodejs/nan#tests
> 
> > ### Tests
> > To run the NAN tests do:
> > ```shell
> > npm install
> > npm run-script rebuild-tests
> > npm test
> > ```
> > 
> > 
> > Or just:
> > ```shell
> > npm install
> > make test
> > ```
> 
> I don't think we currently have a way in `lookup.json` of accommodating this.

My attempt: https://github.com/nodejs/citgm/pull/696

**Comment by targos** [comment]
Superseded by https://github.com/nodejs/citgm/pull/696

**Pull request closed without merging**
