### PR TITLE
lookup: rm hyphen from debian ref for hapi

### PR DESCRIPTION
**Pull request by danielleadams**
##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/HEAD/CONTRIBUTING.md)

### CODE REVIEW

**Comment by danielleadams** [comment]
cc @richardlau

**Review by richardlau — APPROVED** [review]

**Comment by richardlau** [comment]
hmm actually this might not be so straightforward looking at [`lib/match-conditions.js`](https://github.com/nodejs/citgm/blob/71daf46e2c61a66e5c21f567b81869d9474a588d/lib/match-conditions.js). 

We do add a hyphen for platform-arch
https://github.com/nodejs/citgm/blob/71daf46e2c61a66e5c21f567b81869d9474a588d/lib/match-conditions.js#L63 but that's something like `linux-x64`. For `debian` we have `distro` but that's never joined to `release` so I'm not sure how we specify a condition that involves both.

**Comment by targos** [comment]
I'd be okay with simplifying to `debian` in this PR.

**Comment by danielleadams** [comment]
Ok, I updated to just reference `debian`

**Review by richardlau — APPROVED** [review]

**Review by targos — APPROVED** [review]

**Pull request merged**
