### PR TITLE
WIP: bin: add repeat option to citgm-all

### PR DESCRIPTION
**Pull request by gibfahn**
Use `-r 5` or `--repeat 5` to repeat all the modules in the lookup.
Specify `repeat: 5` in the lookup to repeat a single module.

Alternative to https://github.com/nodejs/citgm/pull/383

##### Checklist

- [ ] add `citgm` equivalent
- [ ] `npm test` passes
- [ ] add tests
- [ ] add docs (README and man page)
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gibfahn** [comment]
Note that I haven't yet added tests or docs (that's why the checklist isn't complete). I wanted to get feedback on this approach first.

**Comment by gdams** [comment]
I feel like `citgm-all` is the wrong command here.... surely you would want to use the `citgm` command with repeat? The idea here is that you are repeating a single module and not several

**Comment by MylesBorins** [comment]
what is the status of this?

**Comment by BridgeAR** [comment]
Ping @gibfahn

**Comment by al-k21** [comment]
> I feel like citgm-all is the wrong command here.... surely you would want to use the citgm command with repeat? The idea here is that you are repeating a single module and not several

+1

**Comment by BridgeAR** [comment]
@gibfahn are you still planning on working on this? It would be great to get a update here.

**Comment by MylesBorins** [comment]
This has been stale for over a year. Closing, but feel free to reopen

**Pull request closed without merging**
