### PR TITLE
package: update tap-parser to 9.3.2

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by richardlau** [comment]
Failing on Node.js 6. Given Node.js 6 is almost EOL I've no objections to landing as semver major dropping support for Node.js 6.

**Comment by targos** [comment]
Should we wait until it's really EOL to land this?

**Comment by targos** [comment]
rebased

**Comment by BridgeAR** [comment]
Who has the rights for travis for this repository by the way? I can't restart jobs.

**Comment by richardlau** [comment]
> Who has the rights for travis for this repository by the way? I can't restart jobs.

I can (and just did). Are you signed in to Travis? I’m not sure what governs permissions there but I don’t recall explicitly being given permissions for that.

**Comment by BridgeAR** [comment]
@richardlau I am signed in to Travis. If I recall correct you're a `build` member. That should give you access to most things.

**Comment by richardlau** [comment]
> @richardlau I am signed in to Travis. If I recall correct you're a `build` member. That should give you access to most things.

😆 Ah maybe it is based on me being able to edit citgm-* jobs in our CI — I think there was a GitHub team for that. (I’m not, and have never been, a member of the Build WG.)

**Pull request merged**
