### PR TITLE
lookup: add top depended modules from NPM

### PR DESCRIPTION
**Pull request by TheAlphaNerd**
this includes:
  * async
  * bluebird
  * mkdirp
  * yeoman-generator
  * minimist
  * cheerio
  * node-uuid
  * winston
  * yargs
  * semver
  * mime

### CODE REVIEW

**Comment by jasnell** [comment]
LGTM

**Comment by TheAlphaNerd** [comment]
citgm: https://ci.nodejs.org/job/thealphanerd-smoker/179/

**Comment by TheAlphaNerd** [comment]
LOL... looks like grunt updated to v1 broke almost everything.

Time to clean up

**Comment by shama** [comment]
Sorry about the breakages! We have published `1.0.1` with a fix. Thanks for your help @TheAlphaNerd!

**Comment by TheAlphaNerd** [comment]
my pleasure @shama thanks for the quick turn around!

**Comment by TheAlphaNerd** [comment]
This has been rebased on top of #126 in order to get more granular flaky support... let's test all the things!

master: https://ci.nodejs.org/view/Node.js-citgm/job/thealphanerd-smoker/223/
v6.0.0: https://ci.nodejs.org/view/Node.js-citgm/job/thealphanerd-smoker/224/
v5.11.0: https://ci.nodejs.org/view/Node.js-citgm/job/thealphanerd-smoker/225/
v4.4.3: https://ci.nodejs.org/view/Node.js-citgm/job/thealphanerd-smoker/226/
v0.12.13: https://ci.nodejs.org/view/Node.js-citgm/job/thealphanerd-smoker/227/
v0.10.44: https://ci.nodejs.org/view/Node.js-citgm/job/thealphanerd-smoker/228/

**Comment by TheAlphaNerd** [comment]
mkdirp failures on v6 / master are related to https://github.com/tschaub/mock-fs/pull/107

**Comment by TheAlphaNerd** [comment]
one last CI run on master: https://ci.nodejs.org/view/Node.js-citgm/job/thealphanerd-smoker/230/
if this is good then I'm going to merge these changes. We can fix other problems as they arise

**Comment by TheAlphaNerd** [comment]
landed in e761c99...2e708ce

**Pull request closed without merging**
