### PR TITLE
lookup: mark david as flaky on win32

### PR DESCRIPTION
**Pull request by gdams**
David is failing on windows:
```
C:\Users\jenkins\workspace\SVT-V6-COMMUNITY-CITGM\ARCH\x64\GCC\gcc48\OS\win7\TAG\svt\tmp\3e38cc3b-ceb3-46ea-a311-0b9b1a189dc2\david\node_modules\.bin\tape.CMD:1
 (function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                               ^
 SyntaxError: Invalid or unexpected token
     at Object.exports.runInThisContext (vm.js:76:16)
     at Module._compile (module.js:542:28)
     at Object.Module._extensions..js (module.js:579:10)
     at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\jenkins\workspace\SVT-V6-COMMUNITY-CITGM\ARCH\x64\GCC\gcc48\OS\win7\TAG\svt\tmp\3e38cc3b-ceb3-46ea-a311-0b9b1a189dc2\david\node_modules\istanbul\lib\hook.js:109:37)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3)
     at Function.Module.runMain (module.js:604:10)
     at runFn (C:\Users\jenkins\workspace\SVT-V6-COMMUNITY-CITGM\ARCH\x64\GCC\gcc48\OS\win7\TAG\svt\tmp\3e38cc3b-ceb3-46ea-a311-0b9b1a189dc2\david\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
     at C:\Users\jenkins\workspace\SVT-V6-COMMUNITY-CITGM\ARCH\x64\GCC\gcc48\OS\win7\TAG\svt\tmp\3e38cc3b-ceb3-46ea-a311-0b9b1a189dc2\david\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
```
##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by gdams** [comment]
CC @alanshaw

**Comment by alanshaw** [comment]
?? what is this?

**Comment by gdams** [comment]
We can mark the module as flaky meaning that we expect the module to fail on a certain platform but I wanted to check with you if david was meant to work with windows

**Comment by alanshaw** [comment]
Is it actually this issue that we're coming up against: https://github.com/gotwarlost/istanbul/issues/90

I'm happy to change the test command if it'll help. David *is* supposed to work on windows but the tests are rarely run on windows.

**Comment by gdams** [comment]
Looks like the same issue to me! It would be good to get david working on windows because then we can pick up new failures for you when they occur

**Comment by alanshaw** [comment]
Ok that's done, hope that makes it not flaky :)

**Comment by gdams** [comment]
@alanshaw fixed! thanks for the speedy response

**Pull request closed without merging**
