### PR TITLE
deps: update tar to v3.1.5

### PR DESCRIPTION
**Pull request by targos**
In this new version, the "path" option was replaced by "cwd" and it
appears that the directory is no longer automatically created.

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration/38/

**Comment by MylesBorins** [comment]
Strange that we are seeing the same timeouts on the same tests... we should dig into failures

**Comment by targos** [comment]
Rebased and updated.
New CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration/41/

**Comment by targos** [comment]
Last CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration/42/
Run on master for comparison: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration/43/

Failures seem unrelated

**Pull request merged**
