### PR TITLE
lookup: [linter] remove extra spacing

### PR DESCRIPTION
**Pull request by al-k21**
##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by targos** [comment]
FYI I started maintaining a list of skipped modules in https://github.com/nodejs/citgm/projects/1
I added issue 466 as a reference there for the `ftp` module

**Comment by MylesBorins** [comment]
Afaik we have not had skipIssue as metadata before. If we are going to add this we should likely do it for all modules and document it.

**Comment by targos** [comment]
I'm not strictly opposed to it but I'd prefer if did it in the project page.

**Comment by al-k21** [comment]
Raised https://github.com/nodejs/citgm/issues/547 to discuss.

**Pull request merged**
