### PR TITLE
lookup: zeromq override MSBUILD version

### PR DESCRIPTION
**Pull request by al-k21**
This is failing for a while - https://github.com/zeromq/zeromq.js/issues/231
 
This is not an actual fix more of a workaround while this is not fix. 

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gibfahn** [comment]
Also can you make the `fixes` a `Refs:`? Should also `Refs: https://github.ibm.com/runtimes/squad-node-dragons/issues/842`.

**Comment by gibfahn** [comment]
We'll need a citgm run to make sure this works on ci.nodejs.org

**Comment by al-k21** [comment]
@gibfahn Is it possible for me to get access to ci.nod.org? I'd like to keep helping with CITGM.

**Comment by al-k21** [comment]
I think this is not a good workaround, only works on the machines with a visual studio 2015.

Closing.

**Pull request closed without merging**
