### PR TITLE
lookup: add https-proxy-agent

### PR DESCRIPTION
**Pull request by lpinca**
This package has ~6 million weekly downloads and we broke it in
Node.js 10.0.0

Refs: https://github.com/nodejs/node/issues/24474#issuecomment-511963799

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/86/

**Comment by lpinca** [comment]
@nodejs/citgm ping

**Comment by targos** [comment]
This fails on all supported versions of Node.js:
- 10: https://ci.nodejs.org/job/citgm-smoker-nobuild/838/
- 12: https://ci.nodejs.org/job/citgm-smoker-nobuild/839/
- 13: https://ci.nodejs.org/job/citgm-smoker-nobuild/840/
- 14: https://ci.nodejs.org/job/citgm-smoker-nobuild/837/

**Comment by lpinca** [comment]
Interesting. It seems that a build step (`npm run build`) is required before running tests. There is also a test failure du to recent stream changes.

These issues should be fixed before this can land.

**Comment by targos** [comment]
if there's a build script to run, you can specify it in a "scripts" property.
Example: https://github.com/nodejs/citgm/blob/a6c119bc3bead3e271ded7bfb1bb164ac7047a46/lib/lookup.json#L307

**Comment by lpinca** [comment]
Ok, thanks Michaël. Trying to figure how to fix the failing tests now (this is why I want this in CITGM, we broke this module again).

**Comment by lpinca** [comment]
It should now fail only on Node.js 14 (https://github.com/TooTallNate/node-https-proxy-agent/pull/104).

**Comment by targos** [comment]
Is it possible to cut a release so the module is fixed on Node.js 14 and 15, and we can merge this?

**Comment by lpinca** [comment]
See https://github.com/TooTallNate/node-https-proxy-agent/pull/104#issuecomment-718403478). If maintainers are not responsive I think it does not make sense to add this.

**Comment by targos** [comment]
Is the module entirely broken on Node.js 14+ without the patch from https://github.com/TooTallNate/node-https-proxy-agent/pull/104 ?

**Comment by lpinca** [comment]
Not completely broken, only if the proxy replies with a non 200 status code.

**Comment by lpinca** [comment]
`https-proxy-agent@5.0.1` has been released. This should be finally ready to land.

**Comment by targos** [comment]
could you please rebase so we test the PR with the latest code?

**Comment by targos** [comment]
CI looks good to me. The only failure is due to Ubuntu 18.04 which cannot run node 18.

**Pull request merged**
