### PR TITLE
add package-lock.json

### PR DESCRIPTION
**Pull request by Trott**
The current package-lock.json is out of sync with package.json. (You can
see this by running `npm ci`.) Remove the `.npmrc` file that was
preventing generation of package-lock.json (despite that it is there in
the repository!), regenerate, and commit.

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed
      [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by BridgeAR** [comment]
I would rather not use a package-lock at all. Did we always use one?

**Comment by Trott** [comment]
> I would rather not use a package-lock at all. Did we always use one?

No, it was added in the last commit less than an hour ago.

Why would you rather not use a package-lock.json?

**Comment by MylesBorins** [comment]
I've rebased / force pushed out the change that accidentally added the package-lock... unsure how that slipped in thanks for noticing trott. Might make sense to keep this open specifically around the discussion of having a package lock or not

**Comment by BridgeAR** [comment]
AFAIC a `package-lock` is good for an application but not good for modules. It would prevent to include fixes and we always have to update the package-lock which is quite a hassle.

A package-lock is good in case you want to make sure you get exactly the same modules no matter if I deploy right now or later. Otherwise it's not possible that things behave different depending on the concrete deployed instance. In modules I want to get all updates as soon as possible without having to check for them. If one of them breaks, the dependency range was either wrong or an unintentional semver-major landed in the used dependency.

**Comment by Trott** [comment]
> AFAIC a `package-lock` is good for an application but not good for modules. It would prevent to include fixes and we always have to update the package-lock which is quite a hassle.
> 
> A package-lock is good in case you want to make sure you get exactly the same modules no matter if I deploy right now or later. Otherwise it's not possible that things behave different depending on the concrete deployed instance. In modules I want to get all updates as soon as possible without having to check for them. If one of them breaks, the dependency range was either wrong or an unintentional semver-major landed in the used dependency.

I guess I would think that having the ability to "time travel" by using the package-lock from last week would be useful in something like CITGM. But I don't feel *that* strongly about it, especially since I only infrequently deal directly with CITGM's code. So.... 
¯\\_(ツ)_/¯

**Comment by targos** [comment]
I think CITGM is installed from npm when we run the smoker job, so the package-lock wouldn't be used anyway.

**Pull request closed without merging**
