### PR TITLE
[WIP] citgm-stress: add a citgm stress test

### PR DESCRIPTION
**Pull request by GeorgeAdams95**
ISSUE: https://github.com/nodejs/citgm/issues/122
The idea behind citgm stress is that we can repeat a single module test multiple times without having to repeat the entire npm install process.
You can run citgm-stress using `./bin/citgm-stress.js module -r n` where n is the number of repeats

### CODE REVIEW

**Comment by GeorgeAdams95** [comment]
At the moment I am able to run module tests multiple times but more work is going to be needed. At the moment I get the following error: `if (fn === null) throw new Error("Callback was already called.");` we need to handle returning multiple exit codes to the asyc.waterfall

**Comment by GeorgeAdams95** [comment]
UPDATE: citgm-stress now runs each repeat synchronously which means that the logger information is in the correct order. As of now, we return one overall exit code to the reporter so you get one result instead of how many repeats you passed in.

**Comment by TheAlphaNerd** [comment]
@GeorgeAdams95 where are you on this?

**Comment by GeorgeAdams95** [comment]
@TheAlphaNerd I'm going to close this for now and reopen when some other stuff has been merged in and I've got some time to take a look

**Pull request closed without merging**
