### PR TITLE
lookup: unmark node-report as flaky

### PR DESCRIPTION
**Pull request by richardlau**
I'm on a tablet at the moment so can't test locally but I don't believe node-report tests should be flaky on Windows. 

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by al-k21** [comment]
CI: https://ci.nodejs.org/job/citgm-smoker-nobuild/255/

Failed with [`unexpected end of file`](https://github.com/nodejs/node-gyp/issues/1068), which seem like an transient error. 

As per suggestion in [here](https://github.com/bnoordhuis/node-heapdump/issues/104#issuecomment-305282336) I would like to clean out npm cache.

Apart from that LGTM.

**Comment by gibfahn** [comment]
>As per suggestion in here I would like to clean out npm cache, how could I do that? @gib

The cache is part of the workspace, and is removed as part of each job.

**Comment by richardlau** [comment]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/20/console

**Comment by targos** [comment]
CI: https://ci.nodejs.org/blue/organizations/jenkins/citgm-smoker-pipeline/detail/citgm-smoker-pipeline/32/pipeline

**Comment by richardlau** [comment]
Marked `do not land` until https://github.com/nodejs/node-report/issues/113 is resolved.

**Comment by richardlau** [comment]
> 
> 
> Marked `do not land` until [nodejs/node-report#113](https://github.com/nodejs/node-report/issues/113) is resolved.

https://github.com/nodejs/node-report/pull/118 will resolve the flakiness on Windows. This PR would need a rebase since we sorted `lookup.json`. I've just realised that this PR is a branch in this repository rather than my fork (I think this happened as I used GitHub's web UI to edit `lookup.json`). I'll close this and clean out the branch -- we can unflake this on Windows in a new PR when node-report is updated.

**Pull request closed without merging**
