### PR TITLE
lookup: unskip koa on win32 and rhel

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/219/

**Comment by targos** [comment]
I don't understand what happens here with CI. It's like the tests run twice?

**Comment by targos** [comment]
New CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/228/

**Comment by targos** [comment]
@MylesBorins do you understand those failures? The tests run twice, pass twice, there is a timeout in the middle and sometimes it works correctly (ironically only two passed in the last run and rhel one of these)...

**Comment by targos** [comment]
New CI with Windows included looks good: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/233/

/cc @nodejs/citgm

**Comment by al-k21** [comment]
Seems okay to me [rhel72-s390x](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/252/MACHINE=rhel72-s390x/console).

**Pull request merged**
