### PR TITLE
lookup: unskip ws on win32

### PR DESCRIPTION
**Pull request by lpinca**
Unskip ws on Windows.

##### Checklist

- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by lpinca** [comment]
It seems citgm-smoker-nobuild does not work. Trying with citgm-smoker.

CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1569/

**Comment by lpinca** [comment]
@nodejs/citgm Is there anything I can do to move this and https://github.com/nodejs/citgm/pull/608 forward?

**Comment by targos** [comment]
Results are good on Node 10 and 11 but the job fails to run on 6 and 8 (opened https://github.com/nodejs/build/issues/1602)

**Comment by targos** [comment]
Running citgm-smoker instead:
- v6: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1643/
- v8: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1644/

**Comment by MylesBorins** [comment]
hey @lpinca the pipeine job you tried to run was running for almost 10 hours so I aborted it. Lets dig in and figure out what was taking so long. I think it is that the AIX machine is out of memory

/cc @nodejs/build

**Comment by lpinca** [comment]
Ok, there is also something wrong in the Windows machines.

```
09:24:52 verbose: ws npm:             | Using temp directory: "c:workspacecitgm-smoker-nobuild\citgm_tmp\11e0389e-843f-4c19-bf2c-57dcf7e39917\npm_config_tmp"
09:24:53 info: ws npm:             | npm install successfully completed
09:24:53 info: ws npm:             | test suite started  
09:24:53 verbose: ws npm-test:        | 'node' is not recognized as an internal or external command,
09:24:53 verbose:                     | operable program or batch file.                             
09:24:53 error: failure             | The canary is dead:
```

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/81/console

**Pull request merged**
