### PR TITLE
lookup: skip zeromemq on s390

### PR DESCRIPTION
**Pull request by refack**
Test does not finish on s390
Fixes: #423
Ref: https://ci.nodejs.org/job/citgm-smoker/817/nodes=rhel72-s390x/
Ref: https://gist.github.com/refack/1554480241ded629a0639a741db72cb1

##### Checklist

- [X] `npm test` passes
- [X] tests are included
- [X] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by MylesBorins** [comment]
@refack can you do a filtered version of the output that came from zeromq. Which part of the lifecycle is it getting stalled in. We have timeouts, so it should have been caught. Concern is that this might be a deeper bug manifesting.

[Here is a citgm run of only zeromq](https://ci.nodejs.org/job/citgm-smoker/824/)

**Comment by MylesBorins** [comment]
Based on https://ci.nodejs.org/job/citgm-smoker/824/nodes=rhel72-s390x/console and your above note it would appear that it is getting stalled in the test phase. We currently do not have a timeout in the test phase (we do during install).

Perhaps we should implement one?

**Comment by MylesBorins** [comment]
landed as da9e51e

**Comment by refack** [comment]
Confirmed fix https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/826/nodes=rhel72-s390x/consoleText

**Comment by gibfahn** [comment]
Can be undone once https://github.com/nodejs/citgm/issues/426 lands

**Pull request closed without merging**
