### PR TITLE
4.0.0

### PR DESCRIPTION
**Pull request by targos**
Merge the 4.0.0 release commit to master.

Refs: https://github.com/nodejs/citgm/issues/690

### CODE REVIEW

**Comment by targos** [comment]
I didn't expect you to react so fast 😆 .
I was writing a message suggesting to use the "merge" button this time, so 4.0.0 would be located at the right place in the history.

**Comment by MylesBorins** [comment]
LOL.

Ok, should we revert it? we could also rebase master to get the commit in the right place,... thoughts?

**Comment by targos** [comment]
rebase SGTM

**Comment by MylesBorins** [comment]
done

**Pull request merged**
