### PR TITLE
Added express related modules

### PR DESCRIPTION
**Pull request by wesleytodd**
Added important express related modules:

- [router](https://www.npmjs.com/package/router)
- [path-to-regexp](https://www.npmjs.com/package/path-to-regexp)
- [multer](https://www.npmjs.com/package/multer)
- [express-session](https://www.npmjs.com/package/express-session)
- [body-parser](https://www.npmjs.com/package/body-parser)

<sup>_Edited by @gibfahn to add links to npm_</sup>

##### Checklist

- [X] `npm test` passes
- [X] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gibfahn** [comment]
Could you briefly go through the https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md#submitting-a-module-to-citgm here?

**Comment by wesleytodd** [comment]
@gibfahn Sure!

[x] Module source code must be on Github.
[x] Published versions must include a tag on Github
[x] The test process must be executable with only the commands npm install && npm test using the tarball downloaded from the Github tag mentioned above
[x] The tests pass on supported major release lines
[x] The maintainers of the module remain responsive when there are problems
[x] At least one module maintainer must be added to the lookup maintainers field

At least one of:

[x] The module must be actively used by the community OR
[x] The module must be heavily depended on OR
[ ] The module must cover unique portions of our API OR
[ ] The module fits into a key category (e.g. Testing, Streams, Monitoring, etc.) OR
[ ] The module is under the Node.js foundation Github org OR
[ ] The module is identified as an important module by a Node.js Working Group

I believe that all five modules listed above fit the same criteria.  All of them are maintained by the express ctc, and since express is an incubator project for the node foundation, I believe they qualify as I indicated above.

CC'ing the maintainers listed in case they disagree with my assessment.  @dougwilson @blakeembrey @linusu

**Comment by gdams** [comment]
we need to check if any of these modules have fips support or not.

**Comment by gdams** [comment]
@wesleytodd `mutler`, `router`, `path-to-regexp` and `express-session` are all failing to install because they need a `prefix` tag added to the lookup

**Comment by gibfahn** [comment]
@wesleytodd the process for checking that module tests pass with citgm is documented in https://github.com/nodejs/citgm/pull/416. 

For adding a prefix to the lookup.json, see [lib/lookup.json#L18](https://github.com/nodejs/citgm/blob/master/lib/lookup.json#L18)

**Comment by wesleytodd** [comment]
Updated.  Sorry it took me so long, I hate that github marks notifications read from just opening the email.  I forgot to follow up.

I ran each through on my computer with `node@7.6.0` and they all passed.  Let me know if there is anything else.

**Comment by gdams** [comment]
okay so all of these modules are compatible with FIPS builds

**Comment by MylesBorins** [comment]
landed in efe3f2ac37

**Pull request closed without merging**
