### PR TITLE
lookup: add zeromq

### PR DESCRIPTION
**Pull request by rgbkrk**
This adds the native module `zeromq` to the citgm suite.

##### Checklist

I'm not sure how much of the checklist I need to handle when adding a new lib to lookup. 
¯\\\_(ツ)\_/¯

- [ ] `npm test` passes
- [ ] tests are included
- [ ] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gibfahn** [comment]
For the contribution guidelines, you need to follow: https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md#submitting-a-module-to-citgm

A brief answer to each of the requirements would be helpful.

**Comment by MylesBorins** [comment]
reviewed list and this module seems relevant

landed in be49a6be3b

**Comment by rgbkrk** [comment]
Thanks @gibfahn and @MylesBorins, I was hoping to come back to this soon. Much thanks for this. 😄

**Comment by rgbkrk** [comment]
@lgeiger -- forgot to give you a heads up that zeromq.js is part of the canary in the gold mine suite for node.js now. We'll get called on if something funky is happening with node builds and the package. 😄

**Comment by lgeiger** [comment]
Awesome thanks 👍 😄

**Comment by gdams** [comment]
@MylesBorins can we please run CI on new modules before landing them. This is flaky on s390x and aix-ppc64. Looks like @refack has already landed the s390x skip.

**Pull request closed without merging**
