### PR TITLE
lookup: unskip ember-cli

### PR DESCRIPTION
**Pull request by targos**
Ref: https://github.com/nodejs/citgm/issues/473
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/10/console

### CODE REVIEW

**Comment by targos** [comment]
I don't understand. The tests fail on CI but pass locally:

```console
$ citgm ember-cli
info:    starting            | ember-cli           
info:    lookup              | ember-cli           
info:    lookup-found        | ember-cli           
info:    ember-cli lookup-replace| https://github.com/ember-cli/ember-cli/archive/v2.15.1.tar.gz
info:    ember-cli npm:      | Downloading project: https://github.com/ember-cli/ember-cli/archive/v2.15.1.tar.gz
info:    ember-cli npm:      | Project downloaded ember-cli-2.15.1.tgz
info:    ember-cli npm:      | npm install started 
info:    ember-cli npm:      | npm install successfully completed
info:    ember-cli npm:      | test suite started  
info:    passing module(s)   |                     
info:    module name:        | ember-cli           
info:    version:            | 2.15.1              
info:    done                | The smoke test has passed.
info:    duration            | test duration: 41015ms

```

**Comment by targos** [comment]
Trying again on v8: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/222/

**Comment by targos** [comment]
```
   1 failing
   1) Acceptance: ember new
        ember new uses yarn when blueprint has yarn.lock:
      AssertionError: expected "yarn.lock" to not be empty
       at Context.<anonymous> (tests/acceptance/new-test.js:243:40)
       at Generator.next (<anonymous>)
       at onFulfilled (node_modules/co/index.js:65:19)
       at tryCatcher (node_modules/rsvp/dist/rsvp.js:329:19)
       at invokeCallback (node_modules/rsvp/dist/rsvp.js:507:31)
       at publish (node_modules/rsvp/dist/rsvp.js:493:7)
       at flush (node_modules/rsvp/dist/rsvp.js:2432:5)
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
```

Yarn is required.

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/57/console

**Comment by targos** [comment]
New CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/84/

**Comment by targos** [comment]
Failed once on AIX. Flaky? Rebuild? Give it a chance and land?

**Comment by targos** [comment]
I'll merge. It's easy to skip on a platform or mark flaky if the failure happens again

**Comment by stefanpenner** [comment]
💃

**Pull request merged**
