### PR TITLE
[wip] lookup: add modules to test zlib

### PR DESCRIPTION
**Pull request by MylesBorins**
- compression
- decompress-targz

### CODE REVIEW

**Comment by rvagg** [comment]
nice! :+1:

**Comment by TheAlphaNerd** [comment]
citgm: https://ci.nodejs.org/view/Node.js-citgm/job/thealphanerd-smoker/262/

**Comment by addaleax** [comment]
Hi! Noticed that this is still open and that https://www.npmjs.com/package/yazl / https://www.npmjs.com/package/yauzl might be good candidates, too. :)

**Comment by gdams** [comment]
@MylesBorins are we good to land this? the replace tag obviously needs to be removed now

**Comment by BridgeAR** [comment]
This is highly outdated and should either be closed or the updated.

**Comment by MylesBorins** [comment]
I'm going to close this for now due to inactivity, please feel free to reopen

**Pull request closed without merging**
