### PR TITLE
lookup: unflakey tape on Windows

### PR DESCRIPTION
**Pull request by bzoz**
Tape is no longer falky on Windows

##### Checklist

- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by targos** [comment]
CI: https://ci.nodejs.org/blue/organizations/jenkins/citgm-smoker-pipeline/detail/citgm-smoker-pipeline/28/pipeline

**Comment by targos** [comment]
Tests seem to fail consistently in CI:

https://ci.nodejs.org/job/citgm-smoker-nobuild/330/MACHINE=win2008r2-vs2017/testReport/junit/(root)/citgm/tape_v4_9_1/

**Comment by BridgeAR** [comment]
Ping @bzoz

**Comment by bzoz** [comment]
I cannot get this to reproduce on my win2008 VM. I guess it is some config issue.

Anyhow - the module tests do not pass in the CI, so this should be changed to "skipped".

**Comment by BridgeAR** [comment]
What is the status here?

(Just started a CI even though it seems to fail: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/40/)

**Comment by targos** [comment]
I rebased this on top of `master`, which should be OK to run on Windows. `citgm tape` passes on my Windows machine.
CI: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/54/console

**Comment by targos** [comment]
Apparently CI will run on all platforms even if I selected only windows nodes. If it ends up fully green, I will also remove the linux flakiness

**Comment by targos** [comment]
Landed in 4a3d2dcb44baba90b6b1a98c3094fd8be171b03f

**Pull request closed without merging**
