### PR TITLE
test: fix test-citgm-all on Windows

### PR DESCRIPTION
**Pull request by targos**
Refs: https://github.com/nodejs/citgm/issues/879

### CODE REVIEW

**Comment by targos** [comment]
@nodejs/citgm

**Review by Trott — APPROVED** [review]
I'd rather see us fix the issue, but uh, yeah, that's a taller order and this has been going on for some time so...reluctant 👍 .

**Comment by targos** [comment]
I split the test file to investigate the failing tests. I don't know yet why it fails, but I think it's related to the spaces in the `--includeTags` option.
Tests fail because the child process exits with code 13 instead of 0.

There is nothing indicating that something went wrong in the output:
```
{
  code: 13,
  stdout: 'info: includeTags         | Only running tests matching these tags: tag1 noTag1 NoTag2\r\n' +
    'info: omg-i-pass          | skipped as no includeTags matched\r\n' +
    'info: omg-i-fail          | skipped as no includeTags matched\r\n' +
    'info: omg-i-pass-too      | skipped as no includeTags matched\r\n' +
    'info: done                | The smoke test has passed.\r\n',
  stderr: ''
}
```

**Comment by targos** [comment]
> I think it's related to the spaces in the --includeTags option.

Confirmed, and fixed.

**Review by Trott — APPROVED** [review]

**Pull request merged**
